var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja,ka;
if(ca){var fs=require("fs"),la=require("path");h=__dirname+"/";ia=(a,b)=>{a=ma(a)?new URL(a):la.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a};ja=(a,b,c)=>{a=ma(a)?new URL(a):la.normalize(a);fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof na||a.context instanceof na))throw a;});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ja=(a,b,c)=>{if(ma(a)){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)}else fetch(a,{credentials:"same-origin"}).then(e=>e.ok?e.arrayBuffer():Promise.reject(Error(e.status+" : "+e.url))).then(b,c)};var oa=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);
g.quit&&(ha=g.quit);var q;g.wasmBinary&&(q=g.wasmBinary);var pa,r=!1,t,qa,v,ra,sa,w,x,z,A;function ta(){var a=pa.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAP32=w=new Int32Array(a);g.HEAPU32=x=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=A=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();ua.unshift(a)}var B=0,za=null,C=null;
function Aa(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);r=!0;t=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://"),Ca;function Da(a){if(a==Ca&&q)return new Uint8Array(q);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){return q?Promise.resolve().then(()=>Da(a)):new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),()=>{try{b(Da(a))}catch(d){c(d)}})})}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);Aa(d)})}
function Ga(a,b){var c=Ca;q||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||ma(c)||ca||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}function na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=a=>{for(;0<a.length;)a.shift()(g)},Ia=g.noExitRuntime||!0,Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=(a,b)=>{Ka=a;La=b;if(E)if(Ma||=!0,0==a)F=function(){var d=Math.max(0,Na+b-Oa())|0;setTimeout(G,d)};else if(1==a)F=function(){Pa(G)};else if(2==a){if("undefined"==typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=function(d){c.push(d);ba?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),
postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Qa=setImmediate;F=function(){Qa(G)}}},Oa;Oa=()=>performance.now();
var Za=(a,b,c,d,e)=>{E=a;Sa=d;var k=H;Ma=!1;G=function(){if(!r)if(0<Ta.length){var f=Ta.shift();f.Yc(f.Tc);if(Ua){var l=Ua,n=0==l%1?l-1:Math.floor(l);Ua=f.Vc?n:(8*l+(n+.5))/9}g.setStatus&&(f=g.statusMessage||"Please wait...",l=Ua,n=Va.Xc,l?l<n?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(f):g.setStatus(""));k<H||setTimeout(G,0)}else if(!(k<H))if(Wa=Wa+1|0,1==Ka&&1<La&&0!=Wa%La)F();else{0==Ka&&(Na=Oa());if(!(r||g.preMainLoop&&!1===g.preMainLoop())){if(!r)try{if(a(),!Ia)try{t=
f=t,Xa(f)}catch(p){Ya(p)}}catch(p){Ya(p)}g.postMainLoop?.()}k<H||("object"==typeof SDL&&SDL.audio?.bd?.(),F())}};e||(b&&0<b?Ra(0,1E3/b):Ra(1,1),F());if(c)throw"unwind";},Ya=a=>{a instanceof na||"unwind"==a||ha(1,a)},Xa=a=>{t=a;Ia||(g.onExit?.(a),r=!0);ha(a,new na(a))},$a=a=>{t=a;Xa(a)},Ma=!1,F=null,H=0,E=null,Sa=0,Ka=0,La=0,Wa=0,Ta=[];function ab(){F=null;H++}var Va={},Na,G,Ua,I=!1,bb=!1,cb=[];
function db(){function a(){bb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!eb){eb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!bb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var fb=!1,gb=void 0,J=void 0;
function hb(){if(!I)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ib=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ib)ib=b+1E3/60;else for(;b+2>=ib;)ib+=1E3/60;setTimeout(a,Math.max(ib-b,0))}}var jb=[];function kb(){var a=g.canvas;jb.forEach(b=>b(a.width,a.height))}
function lb(a,b,c){b&&c?(a.Rc=b,a.Oc=c):(b=a.Rc,c=a.Oc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var k=Math.min(screen.width/d,screen.height/e);d=Math.round(d*k);e=Math.round(e*
k)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Qa,eb,mb=0,nb=[];
function ob(){if(navigator.userActivation?navigator.userActivation.isActive:mb&&pb.sc)for(var a=0;a<nb.length;++a){var b=nb[a];nb.splice(a,1);--a;b.gd(...b.Uc)}}var K=[];function qb(a){var b=K[a];b.target.removeEventListener(b.fc,b.zc,b.hc);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.ic)a.zc=function(c){++mb;pb=a;ob();a.jc(c);ob();--mb},a.target.addEventListener(a.fc,a.zc,a.hc),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].fc==a.fc&&qb(b--);return 0}
function rb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var pb,sb,tb,ub,vb,wb,xb,yb,zb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?D(v,a):"":a;return zb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ab=a=>0>zb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Bb=[],Cb,N=a=>{var b=Bb[a];b||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=b=Cb.get(a));return b},O=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var l=
a.charCodeAt(++k);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Db=(a,b,c,d,e,k)=>{sb||=P(256);a={target:M(a),fc:k,ic:d,jc:(f=event)=>{var l=f.target.id?f.target.id:"",n=sb;O(rb(f.target),n+0,128);O(l,n+128,128);N(d)(e,n,b)&&f.preventDefault()},hc:c};return L(a)},Eb=(a,
b,c,d,e,k)=>{tb||=P(176);a={target:M(a),fc:k,ic:d,jc:f=>{var l=tb;A[l>>3]=f.timeStamp;var n=l>>2;w[n+2]=f.location;w[n+3]=f.ctrlKey;w[n+4]=f.shiftKey;w[n+5]=f.altKey;w[n+6]=f.metaKey;w[n+7]=f.repeat;w[n+8]=f.charCode;w[n+9]=f.keyCode;w[n+10]=f.which;O(f.key||"",l+44,32);O(f.code||"",l+76,32);O(f.char||"",l+108,32);O(f.locale||"",l+140,32);N(d)(e,l,b)&&f.preventDefault()},hc:c};return L(a)},Fb=(a,b,c)=>{A[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+
6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=Ab(c);w[a+13]=b.clientX-(c.left|0);w[a+14]=b.clientY-(c.top|0)},Gb=(a,b,c,d,e,k)=>{ub||=P(72);a=M(a);return L({target:a,sc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,fc:k,ic:d,jc:(f=event)=>{Fb(ub,f,a);N(d)(e,ub,b)&&f.preventDefault()},hc:c})},Hb=(a,b,c,d,e)=>{vb||=P(260);return L({target:a,fc:e,ic:d,jc:(k=event)=>{var f=vb,l=document.pointerLockElement||
document.mc||document.Bc||document.Ac;w[f>>2]=!!l;var n=l?.id||"";O(rb(l),f+4,128);O(n,f+132,128);N(d)(20,f,b)&&k.preventDefault()},hc:c})},Ib=(a,b,c,d,e)=>L({target:a,fc:e,ic:d,jc:(k=event)=>{N(d)(38,0,b)&&k.preventDefault()},hc:c}),Jb=(a,b,c,d)=>{wb||=P(36);a=M(a);return L({target:a,fc:"resize",ic:d,jc:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=wb;w[f>>2]=0;w[f+4>>2]=k.clientWidth;w[f+8>>2]=k.clientHeight;w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+24>>
2]=outerHeight;w[f+28>>2]=pageXOffset|0;w[f+32>>2]=pageYOffset|0;N(d)(10,f,b)&&e.preventDefault()}}},hc:c})},Kb=(a,b,c,d,e,k)=>{xb||=P(1696);a=M(a);return L({target:a,sc:"touchstart"==k||"touchend"==k,fc:k,ic:d,jc:f=>{for(var l,n={},p=f.touches,u=0;u<p.length;++u)l=p[u],l.Cc=l.Dc=0,n[l.identifier]=l;for(u=0;u<f.changedTouches.length;++u)l=f.changedTouches[u],l.Cc=1,n[l.identifier]=l;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].Dc=1;p=xb;A[p>>3]=f.timeStamp;var y=p>>2;w[y+
3]=f.ctrlKey;w[y+4]=f.shiftKey;w[y+5]=f.altKey;w[y+6]=f.metaKey;y+=7;var Mb=Ab(a),Nb=0;for(u in n)if(l=n[u],w[y]=l.identifier,w[y+1]=l.screenX,w[y+2]=l.screenY,w[y+3]=l.clientX,w[y+4]=l.clientY,w[y+5]=l.pageX,w[y+6]=l.pageY,w[y+7]=l.Cc,w[y+8]=l.Dc,w[y+9]=l.clientX-(Mb.left|0),w[y+10]=l.clientY-(Mb.top|0),y+=13,31<++Nb)break;w[p+8>>2]=Nb;N(d)(e,p,b)&&f.preventDefault()},hc:c})},Lb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>b.drawElementsInstancedANGLE(c,d,e,k,f))},Ob=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Pb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Qb=a=>{a.Wc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Rb=a=>{a.Zc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Sb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Tb=1,Ub=[],Q=[],Vb=[],Wb=[],Xb=[],R=[],Yb=[],Zb=[],S=[],$b={},ac=4,bc=0,cc=a=>{for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b},dc=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=T[c](),f=k&&cc(d);k?(k.name=f,d[f]=k):U||=1282;w[b+4*e>>2]=f}},fc=(a,b)=>{a.mc||(a.mc=a.getContext,a.getContext=function(d,e){e=a.mc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.uc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?ec(c,b):0},ec=(a,b)=>{var c=cc(Zb),d={handle:c,attributes:b,version:b.uc,oc:a};a.canvas&&(a.canvas.Sc=d);Zb[c]=d;("undefined"==typeof b.yc||b.yc)&&gc(d);return c},hc=a=>{V=Zb[a];g.tc=T=V?.oc;return!(a&&!T)},gc=a=>{a||=V;if(!a.Pc){a.Pc=!0;var b=a.oc;Lb(b);Ob(b);Pb(b);Qb(b);Rb(b);2<=a.version&&(b.xc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.xc)b.xc=b.getExtension("EXT_disjoint_timer_query");b.Qc=b.getExtension("WEBGL_multi_draw");Sb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},ic={},U,V,jc=(a,b,c,d,e,k)=>{a={target:M(a),fc:k,ic:d,jc:(f=event)=>{N(d)(e,0,b)&&f.preventDefault()},hc:c};L(a)},kc=(a,b,c,d)=>{yb||=P(104);return L({target:a,sc:!0,fc:"wheel",ic:d,jc:(e=event)=>{var k=yb;Fb(k,e,a);A[k+72>>3]=e.deltaX;A[k+80>>3]=e.deltaY;A[k+88>>3]=e.deltaZ;w[k+96>>2]=e.deltaMode;N(d)(9,k,b)&&e.preventDefault()},hc:c})},lc=["default","low-power","high-performance"],mc=[null,[],[]];
function nc(){var a=Sb(T);return a=a.concat(a.map(b=>"GL_"+b))}
var oc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=nc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else U||=1281},pc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},qc=a=>{var b=pc(a)+1,c=P(b);c&&O(a,c,b);return c},rc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),sc=[],tc=a=>{a-=5120;return 0==a?qa:1==a?v:2==a?ra:4==a?w:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?x:sa},uc=(a,b,c,d,e)=>{a=tc(a);b=d*((bc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ac-1&-ac);return a.subarray(e>>>
31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=T.Mc;if(b){var c=b.nc[a];"number"==typeof c&&(b.nc[a]=c=T.getUniformLocation(b,b.Kc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],vc=[],xc=a=>{var b=pc(a)+1,c=wc(b);O(a,c,b);return c},Ac=a=>{var b=yc();a();zc(b)};
g.requestFullscreen=function(a,b){function c(){I=!1;var k=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===k?(d.exitFullscreen=hb,gb&&d.requestPointerLock(),I=!0,J?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),lb(g.canvas),kb()):lb(d)):(k.parentNode.insertBefore(d,k),k.parentNode.removeChild(k),J?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>
2]&-8388609),lb(g.canvas),kb()):lb(d));g.onFullScreen?.(I);g.onFullscreen?.(I)}gb=a;J=b;"undefined"==typeof gb&&(gb=!0);"undefined"==typeof J&&(J=!1);var d=g.canvas;fb||(fb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.requestAnimationFrame=Pa;g.setCanvasSize=function(a,b,c){lb(g.canvas,a,b);c||kb()};g.pauseMainLoop=ab;g.resumeMainLoop=function(){H++;var a=Ka,b=La,c=E;E=null;Za(c,0,!1,Sa,!0);Ra(a,b);F()};
g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=function(a,b,c,d){if(b&&g.tc&&a==g.canvas)return g.tc;var e;if(b){var k={antialias:!1,alpha:!1,uc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)k[f]=d[f];if("undefined"!=typeof ic&&(e=fc(a,k)))var l=Zb[e].oc}else l=a.getContext("2d");if(!l)return null;c&&(g.tc=l,b&&hc(e),g.hd=b,cb.forEach(n=>n()),db());return l};
for(var T,Y=0;32>Y;++Y)sc.push(Array(Y));var Bc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Bc.subarray(0,Y);var Cc=new Int32Array(288);for(Y=0;288>Y;++Y)vc[Y]=Cc.subarray(0,Y);
var Mc={Ga:function(){return 0},rb:function(){return 0},sb:function(){},tb:()=>{Aa("")},mb:()=>1,ob:(a,b,c)=>v.copyWithin(a,b,b+c),bb:()=>{ab();E=null},Ea:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Ka:(a,b,c)=>{a=M(a);if(!a)return-4;a=Ab(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},y:Oa,cb:()=>performance.now(),jb:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},nb:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=
b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-pa.buffer.byteLength+65535)/65536;try{pa.grow(e);ta();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},ma:(a,b,c,d)=>Db(a,b,c,d,12,"blur"),Da:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},na:(a,b,c,d)=>Db(a,b,c,d,13,"focus"),wa:(a,b,c,d)=>Eb(a,b,c,d,2,"keydown"),ua:(a,b,c,d)=>Eb(a,b,c,d,1,"keypress"),va:(a,b,c,d)=>Eb(a,b,c,d,3,"keyup"),kb:(a,b,c)=>{a=N(a);
Za(a,b,c)},Ca:(a,b,c,d)=>Gb(a,b,c,d,5,"mousedown"),za:(a,b,c,d)=>Gb(a,b,c,d,33,"mouseenter"),ya:(a,b,c,d)=>Gb(a,b,c,d,34,"mouseleave"),Aa:(a,b,c,d)=>Gb(a,b,c,d,8,"mousemove"),Ba:(a,b,c,d)=>Gb(a,b,c,d,6,"mouseup"),pa:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.mc||document.body.Bc||document.body.Ac))return-1;a=M(a);if(!a)return-4;Hb(a,b,c,d,"mozpointerlockchange");Hb(a,b,c,d,"webkitpointerlockchange");Hb(a,b,c,d,"mspointerlockchange");return Hb(a,b,c,
d,"pointerlockchange")},oa:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.mc||document.body.Bc||document.body.Ac))return-1;a=M(a);if(!a)return-4;Ib(a,b,c,d,"mozpointerlockerror");Ib(a,b,c,d,"webkitpointerlockerror");Ib(a,b,c,d,"mspointerlockerror");return Ib(a,b,c,d,"pointerlockerror")},Ha:(a,b,c,d)=>Jb(a,b,c,d),qa:(a,b,c,d)=>Kb(a,b,c,d,25,"touchcancel"),ra:(a,b,c,d)=>Kb(a,b,c,d,23,"touchend"),sa:(a,b,c,d)=>Kb(a,b,c,d,24,"touchmove"),ta:(a,b,c,d)=>Kb(a,b,c,d,22,"touchstart"),
la:(a,b,c,d)=>{jc(a,b,c,d,31,"webglcontextlost");return 0},ka:(a,b,c,d)=>{jc(a,b,c,d,32,"webglcontextrestored");return 0},xa:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?kc(a,b,c,d):-1:-4,ib:(a,b)=>{b>>=2;b={alpha:!!w[b],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:lc[w[b+6]],failIfMajorPerformanceCaveat:!!w[b+7],uc:w[b+8],$c:w[b+9],yc:w[b+10],Nc:w[b+11],ad:w[b+12],cd:w[b+13]};a=M(a);return!a||b.Nc?0:fc(a,b)},fb:(a,
b)=>{a=Zb[a];b=b?D(v,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Lb(T);"OES_vertex_array_object"==b&&Ob(T);"WEBGL_draw_buffers"==b&&Pb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Qb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Rb(T);"WEBGL_multi_draw"==b&&(T.Qc=T.getExtension("WEBGL_multi_draw"));return!!a.oc.getExtension(b)},gb:a=>hc(a)?0:-5,Fa:()=>52,qb:()=>52,lb:function(){return 70},pb:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var f=x[b>>2],
l=x[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=v[f+n],u=mc[a];0===p||10===p?((1===a?oa:m)(D(u,0)),u.length=0):u.push(p)}e+=l}x[d>>2]=e;return 0},l:a=>T.activeTexture(a),v:(a,b)=>{T.attachShader(Q[a],R[b])},Ja:(a,b,c)=>{T.bindAttribLocation(Q[a],b,c?D(v,c):"")},c:(a,b)=>{35051==a?T.wc=b:35052==a&&(T.kc=b);T.bindBuffer(a,Ub[b])},a:(a,b,c)=>{T.bindBufferBase(a,b,Ub[c])},C:(a,b)=>{T.bindFramebuffer(a,Vb[b])},Va:(a,b)=>{T.bindRenderbuffer(a,Wb[b])},o:(a,b)=>{T.bindSampler(a,S[b])},b:(a,b)=>{T.bindTexture(a,
Xb[b])},ja:a=>{T.bindVertexArray(Yb[a])},ga:(a,b,c,d)=>T.blendColor(a,b,c,d),ha:(a,b)=>T.blendEquationSeparate(a,b),L:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),yb:(a,b,c,d,e,k,f,l,n,p)=>T.blitFramebuffer(a,b,c,d,e,k,f,l,n,p),aa:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,v,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?v.subarray(c,c+b):b,d)},$:(a,b,c,d)=>{2<=V.version?c&&T.bufferSubData(a,b,v,d,c):T.bufferSubData(a,b,v.subarray(d,d+c))},Lb:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),Na:(a,b,c)=>{T.clearBufferfv(a,
b,z,c>>2)},Kb:(a,b,c)=>{T.clearBufferiv(a,b,w,c>>2)},j:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},T:a=>{T.compileShader(R[a])},Ta:(a,b,c,d,e,k,f,l)=>{2<=V.version?T.kc||!f?T.compressedTexImage2D(a,b,c,d,e,k,f,l):T.compressedTexImage2D(a,b,c,d,e,k,v,l,f):T.compressedTexImage2D(a,b,c,d,e,k,l?v.subarray(l,l+f):null)},Sa:(a,b,c,d,e,k,f,l,n)=>{T.kc?T.compressedTexImage3D(a,b,c,d,e,k,f,l,n):T.compressedTexImage3D(a,b,c,d,e,k,f,v,n,l)},Y:()=>{var a=cc(Q),b=T.createProgram();b.name=a;b.rc=b.pc=b.qc=0;b.vc=
1;Q[a]=b;return a},V:a=>{var b=cc(R);R[b]=T.createShader(a);return b},J:a=>T.cullFace(a),ea:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ub[d];e&&(T.deleteBuffer(e),e.name=0,Ub[d]=null,d==T.wc&&(T.wc=0),d==T.kc&&(T.kc=0))}},u:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Vb[d];e&&(T.deleteFramebuffer(e),e.name=0,Vb[d]=null)}},I:a=>{if(a){var b=Q[a];b?(T.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},da:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Wb[d];e&&(T.deleteRenderbuffer(e),e.name=
0,Wb[d]=null)}},ca:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=S[d];e&&(T.deleteSampler(e),e.name=0,S[d]=null)}},s:a=>{if(a){var b=R[a];b?(T.deleteShader(b),R[a]=null):U||=1281}},w:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Xb[d];e&&(T.deleteTexture(e),e.name=0,Xb[d]=null)}},Xa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];T.deleteVertexArray(Yb[d]);Yb[d]=null}},N:a=>T.depthFunc(a),M:a=>{T.depthMask(!!a)},d:a=>T.disable(a),x:a=>{T.disableVertexAttribArray(a)},i:(a,b,c)=>{T.drawArrays(a,
b,c)},Ab:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Bb:(a,b,c,d)=>{T.drawElements(a,b,c,d)},Cb:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},f:a=>T.enable(a),P:a=>{T.enableVertexAttribArray(a)},vb:()=>T.finish(),K:a=>T.frontFace(a),ba:(a,b)=>{dc(a,b,"createBuffer",Ub)},Wa:(a,b)=>{dc(a,b,"createRenderbuffer",Wb)},Qa:(a,b)=>{dc(a,b,"createSampler",S)},_:(a,b)=>{dc(a,b,"createTexture",Xb)},ab:(a,b)=>{dc(a,b,"createVertexArray",Yb)},ub:a=>T.generateMipmap(a),Mb:(a,b)=>T.getAttribLocation(Q[a],b?
D(v,b):""),g:()=>{var a=T.getError()||U;U=0;return a},h:(a,b)=>oc(a,b),W:(a,b,c,d)=>{a=T.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(w[c>>2]=b)},F:(a,b,c)=>{if(c)if(a>=Tb)U||=1281;else if(a=Q[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.rc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.rc=Math.max(a.rc,T.getActiveUniform(a,b).name.length+1);w[c>>2]=a.rc}else if(35722==b){if(!a.pc)for(b=0;b<T.getProgramParameter(a,
35721);++b)a.pc=Math.max(a.pc,T.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.pc}else if(35381==b){if(!a.qc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.qc=Math.max(a.qc,T.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.qc}else w[c>>2]=T.getProgramParameter(a,b);else U||=1281},S:(a,b,c,d)=>{a=T.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(w[c>>2]=b)},D:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==
b?(a=T.getShaderSource(R[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=T.getShaderParameter(R[a],b):U||=1281},$a:(a,b)=>{if(2>V.version)return U||=1282,0;var c=$b[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=nc().map(qc),c=$b[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},n:(a,b)=>{b=b?D(v,b):"";if(a=Q[a]){var c=a,d=c.nc,e=c.Lc,k;if(!d)for(c.nc=d={},c.Kc={},k=0;k<T.getProgramParameter(c,35718);++k){var f=T.getActiveUniform(c,k);var l=f.name;f=f.size;var n=
rc(l);n=0<n?l.slice(0,n):l;var p=c.vc;c.vc+=f;e[n]=[f,p];for(l=0;l<f;++l)d[p]=l,c.Kc[p++]=n}c=a.nc;d=0;e=b;k=rc(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Lc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},xb:(a,b,c)=>{for(var d=sc[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];T.invalidateFramebuffer(a,d)},X:a=>{a=Q[a];T.linkProgram(a);a.nc=0;a.Lc={}},e:(a,b)=>{3317==a?ac=b:3314==a&&(bc=b);T.pixelStorei(a,b)},fa:(a,b)=>T.polygonOffset(a,b),zb:a=>T.readBuffer(a),
Ua:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),Z:(a,b,c)=>{T.samplerParameterf(S[a],b,c)},k:(a,b,c)=>{T.samplerParameteri(S[a],b,c)},A:(a,b,c,d)=>T.scissor(a,b,c,d),U:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=(f=x[c+4*k>>2])?D(v,f,d?x[d+4*k>>2]:void 0):"";e+=f}T.shaderSource(R[a],e)},m:(a,b,c)=>T.stencilFunc(a,b,c),Ma:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),r:a=>T.stencilMask(a),p:(a,b,c)=>T.stencilOp(a,b,c),z:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),G:(a,b,c,d,e,k,f,l,n)=>{if(2<=
V.version){if(T.kc){T.texImage2D(a,b,c,d,e,k,f,l,n);return}if(n){var p=tc(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,k,f,l,p,n);return}}p=n?uc(l,f,d,e,n):null;T.texImage2D(a,b,c,d,e,k,f,l,p)},Ra:(a,b,c,d,e,k,f,l,n,p)=>{if(T.kc)T.texImage3D(a,b,c,d,e,k,f,l,n,p);else if(p){var u=tc(n);T.texImage3D(a,b,c,d,e,k,f,l,n,u,p>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,k,f,l,n,null)},t:(a,b,c)=>T.texParameteri(a,b,c),wb:(a,b,c,d,e,k,f,l,n)=>{if(2<=V.version){if(T.kc){T.texSubImage2D(a,
b,c,d,e,k,f,l,n);return}if(n){var p=tc(l);T.texSubImage2D(a,b,c,d,e,k,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}n=n?uc(l,f,e,k,n):null;T.texSubImage2D(a,b,c,d,e,k,f,l,n)},Jb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),z,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},E:(a,b)=>{T.uniform1i(W(a),b)},Hb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),w,c>>2,b);else{if(288>=b)for(var d=vc[b],e=0;e<b;++e)d[e]=w[c+
4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},La:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),w,c>>2,2*b);else{if(144>=b)for(var d=vc[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&
T.uniform3fv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=vc[3*b],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},O:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=
X[4*b],e=z;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=z.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),w,c>>2,4*b);else{if(72>=b)for(var d=vc[4*b],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},Db:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=
b){var e=X[16*b],k=z;d>>=2;for(var f=0;f<16*b;f+=16){var l=d+f;e[f]=k[l];e[f+1]=k[l+1];e[f+2]=k[l+2];e[f+3]=k[l+3];e[f+4]=k[l+4];e[f+5]=k[l+5];e[f+6]=k[l+6];e[f+7]=k[l+7];e[f+8]=k[l+8];e[f+9]=k[l+9];e[f+10]=k[l+10];e[f+11]=k[l+11];e[f+12]=k[l+12];e[f+13]=k[l+13];e[f+14]=k[l+14];e[f+15]=k[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},q:a=>{a=Q[a];T.useProgram(a);T.Mc=a},ia:(a,b)=>{T.vertexAttribDivisor(a,b)},Q:(a,b,c,d,e,k)=>{T.vertexAttribPointer(a,b,c,!!d,e,k)},B:(a,b,
c,d)=>T.viewport(a,b,c,d),Ob:function(){g.Ec=a=>{0!=Dc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Ec)},hb:function(){g.Jc=a=>{const b=a.clipboardData.getData("text");Ac(()=>{const c=xc(b);Ec(c)})};window.addEventListener("paste",g.Jc)},_a:function(a){g.dd=[];a=a?D(v,a):"";a=document.getElementById(a);g.Fc=b=>{b.stopPropagation();b.preventDefault()};g.Gc=b=>{b.stopPropagation();b.preventDefault()};g.Hc=b=>{b.stopPropagation();b.preventDefault()};g.Ic=b=>{b.stopPropagation();
b.preventDefault();const c=b.dataTransfer.files;g.ed=c;Fc(c.length);for(let e=0;e<c.length;e++)Ac(()=>{const k=xc(c[e].name);Gc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Hc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Fc,!1);a.addEventListener("dragleave",g.Gc,!1);a.addEventListener("dragover",g.Hc,!1);a.addEventListener("drop",g.Ic,!1)},Ya:function(a){a=a?D(v,a):"";g.lc=document.getElementById(a);g.lc||console.log("sokol_app.h: invalid target:"+
a);g.lc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Nb:function(){window.removeEventListener("beforeunload",g.Ec)},eb:function(){window.removeEventListener("paste",g.Jc)},Za:function(a){a=a?D(v,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Fc);a.removeEventListener("dragleave",g.Gc);a.removeEventListener("dragover",g.Hc);a.removeEventListener("drop",g.Ic)},H:function(){g.lc&&g.lc.requestPointerLock&&g.lc.requestPointerLock()},
Pa:function(a,b){if(g.lc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.lc.style.cursor=a}},db:function(a){a=a?D(v,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect",
"off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},R:function(a,b,c,d,e,k){b=b?D(v,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==
f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=k?(v.set(n,e),Ic(a,d,p)):Jc(a)}else Kc(a,f.status)};f.send()},Oa:function(a,b){b=b?D(v,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Lc(a,d)}else Kc(a,c.status)};c.send()},Ia:function(){return navigator.userAgent.includes("Macintosh")?1:0}},Z=function(){function a(c){Z=c.exports;pa=Z.Pb;
ta();Cb=Z.bc;va.unshift(Z.Qb);B--;g.monitorRunDependencies?.(B);0==B&&(null!==za&&(clearInterval(za),za=null),C&&(c=C,C=null,c()));return Z}var b={a:Mc};B++;g.monitorRunDependencies?.(B);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ca||=Ba("hello-touch.wasm")?"hello-touch.wasm":g.locateFile?g.locateFile("hello-touch.wasm",h):h+"hello-touch.wasm";Ga(b,function(c){a(c.instance)});return{}}(),Ec=g.__sapp_emsc_onpaste=
a=>(Ec=g.__sapp_emsc_onpaste=Z.Rb)(a),Dc=g.__sapp_html5_get_ask_leave_site=()=>(Dc=g.__sapp_html5_get_ask_leave_site=Z.Sb)(),Fc=g.__sapp_emsc_begin_drop=a=>(Fc=g.__sapp_emsc_begin_drop=Z.Tb)(a),Gc=g.__sapp_emsc_drop=(a,b)=>(Gc=g.__sapp_emsc_drop=Z.Ub)(a,b),Hc=g.__sapp_emsc_end_drop=(a,b,c)=>(Hc=g.__sapp_emsc_end_drop=Z.Vb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Wb)(a,b,c,d,e,k,f,l);
var Nc=g._main=(a,b)=>(Nc=g._main=Z.Xb)(a,b),Lc=g.__sfetch_emsc_head_response=(a,b)=>(Lc=g.__sfetch_emsc_head_response=Z.Yb)(a,b),Ic=g.__sfetch_emsc_get_response=(a,b,c)=>(Ic=g.__sfetch_emsc_get_response=Z.Zb)(a,b,c),Kc=g.__sfetch_emsc_failed_http_status=(a,b)=>(Kc=g.__sfetch_emsc_failed_http_status=Z._b)(a,b),Jc=g.__sfetch_emsc_failed_buffer_too_small=a=>(Jc=g.__sfetch_emsc_failed_buffer_too_small=Z.$b)(a),P=a=>(P=Z.ac)(a),zc=a=>(zc=Z.cc)(a),wc=a=>(wc=Z.dc)(a),yc=()=>(yc=Z.ec)(),Oc;
C=function Pc(){Oc||Qc();Oc||(C=Pc)};function Rc(a=[]){var b=Nc;a.unshift(fa);var c=a.length,d=wc(4*(c+1)),e=d;a.forEach(f=>{x[e>>2]=xc(f);e+=4});x[e>>2]=0;try{var k=b(c,d);$a(k)}catch(f){Ya(f)}}
function Qc(){var a=ea;function b(){if(!Oc&&(Oc=!0,g.calledRun=!0,!r)){Ha(va);Ha(wa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Sc&&Rc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();xa.unshift(c)}Ha(xa)}}if(!(0<B)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();Ha(ua);0<B||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Sc=!0;g.noInitialRun&&(Sc=!1);Qc();
