
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in f)f.hasOwnProperty(l)&&(k[l]=f[l]);function q(a,b){throw b;}var aa=!1,t=!1,ba=!1,ca=!1;aa="object"===typeof window;t="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!aa&&!ba&&!t;var u="",da,v,ea,fa;
if(ba)u=t?require("path").dirname(u)+"/":__dirname+"/",da=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,b?null:"utf8")},v=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;}),process.on("unhandledRejection",w),
q=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),v=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(q=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:
print);else if(aa||t)t?u=self.location.href:document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ja=f.print||console.log.bind(console),x=f.printErr||console.warn.bind(console);
for(l in k)k.hasOwnProperty(l)&&(f[l]=k[l]);k=null;f.quit&&(q=f.quit);function ka(a){la||(la={});la[a]||(la[a]=1,x(a))}var la,y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&w("no native wasm support detected");var z,A=new WebAssembly.Table({initial:149,maximum:149,element:"anyfunc"}),C=!1;function assert(a,b){a||w("Assertion failed: "+b)}var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?na(E,a,b):""}
function F(a,b,c){var d=E;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-e}var oa,pa,E,qa,ra,G,sa,H,I;
function ta(a){oa=a;f.HEAP8=pa=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAP32=G=new Int32Array(a);f.HEAPU8=E=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAPU32=sa=new Uint32Array(a);f.HEAPF32=H=new Float32Array(a);f.HEAPF64=I=new Float64Array(a)}var ua=f.INITIAL_MEMORY||33554432;f.wasmMemory?z=f.wasmMemory:z=new WebAssembly.Memory({initial:ua/65536,maximum:32768});z&&(oa=z.buffer);ua=oa.byteLength;ta(oa);var va=[],wa=[],xa=[],ya=[],za=[];
function Aa(){var a=f.preRun.shift();va.unshift(a)}var J=0,Ba=null,Ca=null;f.preloadedImages={};f.preloadedAudios={};function w(a){if(f.onAbort)f.onAbort(a);x(a);C=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Da(a){var b=K;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ea(){return Da("data:application/octet-stream;base64,")}var K="KruhStvorec.wasm";if(!Ea()){var Fa=K;K=f.locateFile?f.locateFile(Fa,u):u+Fa}
function Ga(){try{if(y)return new Uint8Array(y);if(v)return v(K);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}function Ha(){return y||!aa&&!t||"function"!==typeof fetch||Da("file://")?Promise.resolve().then(Ga):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ga()})}wa.push({ub:function(){Ia()}});
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.ub;"number"===typeof c?void 0===b.jb?A.get(c)():A.get(c)(b.jb):c(void 0===b.jb?null:b.jb)}}}var Ka=[null,[],[]],La={},Ma=0;function Na(){for(var a=L.length-1;0<=a;--a)Oa(a);L=[];Pa=[]}var Pa=[];function Qa(){if(Ma&&Ra.ob)for(var a=0;a<Pa.length;++a){var b=Pa[a];Pa.splice(a,1);--a;b.Rb.apply(null,b.Eb)}}var L=[];function Oa(a){var b=L[a];b.target.removeEventListener(b.fb,b.xb,b.ib);L.splice(a,1)}
function Sa(a){function b(d){++Ma;Ra=a;Qa();a.mb(d);Qa();--Ma}if(a.kb)a.xb=b,a.target.addEventListener(a.fb,b,a.ib),L.push(a),Ta||(ya.push(Na),Ta=!0);else for(var c=0;c<L.length;++c)L[c].target==a.target&&L[c].fb==a.fb&&Oa(c--)}var Ta,Ra,Ua,Wa,Xa,Ya,Za=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function M(a){a=2<a?D(a):a;return Za[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function $a(a){return 0>Za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function ab(a,b,c,d,e,g){Ua||(Ua=N(164));a={target:M(a),ob:!0,fb:g,kb:d,mb:function(h){var m=Ua,n=m>>2;G[n]=h.location;G[n+1]=h.ctrlKey;G[n+2]=h.shiftKey;G[n+3]=h.altKey;G[n+4]=h.metaKey;G[n+5]=h.repeat;G[n+6]=h.charCode;G[n+7]=h.keyCode;G[n+8]=h.which;F(h.key||"",m+36,32);F(h.code||"",m+68,32);F(h.char||"",m+100,32);F(h.locale||"",m+132,32);A.get(d)(e,m,b)&&h.preventDefault()},ib:c};Sa(a)}
var O=null,P=0,bb=null,cb=0,db=0,eb=0,fb=0,gb=[],hb={},ib,jb,kb,lb=!1,mb=!1,nb=[];
function ob(){function a(){mb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!pb){pb=!0;try{qb=!0}catch(c){qb=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}rb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:qb?null:console.log("warning: no BlobBuilder");
sb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;f.vb||"undefined"!==typeof sb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.vb=!0);f.preloadPlugins.push({canHandle:function(c){return!f.vb&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(qb)try{h=new Blob([c],{type:tb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:tb(d)}))}catch(p){ka("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new rb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=sb.createObjectURL(h),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);f.preloadedImages[d]=p;sb.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};n.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Ob&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(B){n||(n=!0,f.preloadedAudios[d]=B,e&&e(c))}function m(){n||(n=!0,f.preloadedAudios[d]=new Audio,g&&g())}var n=!1;if(qb){try{var p=new Blob([c],{type:tb(d)})}catch(B){return m()}p=sb.createObjectURL(p);var r=new Audio;r.addEventListener("canplaythrough",function(){h(r)},!1);r.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var B="",ia=0,S=
0,Va=0;Va<c.length;Va++)for(ia=ia<<8|c[Va],S+=8;6<=S;){var bc=ia>>S-6&63;S-=6;B+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[bc]}2==S?(B+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(ia&3)<<4],B+="=="):4==S&&(B+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(ia&15)<<2],B+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+B;h(r)}};r.src=p;ub(function(){h(r)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||
b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,
!1),f.elementPointerLock&&b.addEventListener("click",function(c){!mb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function vb(a,b,c,d){if(b&&f.pb&&a==f.canvas)return f.pb;var e;if(b){var g={antialias:!1,alpha:!1,qb:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof wb&&(e=xb(a,g)))var m=yb[e].nb}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof Q,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.pb=m,b&&zb(e),f.Sb=b,nb.forEach(function(n){n()}),ob());return m}var Ab=!1,Bb=void 0,R=void 0;
function Cb(a,b){function c(){lb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Db,Bb&&d.requestPointerLock(),lb=!0,R?("undefined"!=typeof SDL&&(G[SDL.screen>>2]=sa[SDL.screen>>2]|8388608),Eb(f.canvas),Fb()):Eb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),R?("undefined"!=typeof SDL&&(G[SDL.screen>>2]=sa[SDL.screen>>2]&
-8388609),Eb(f.canvas),Fb()):Eb(d));if(f.onFullScreen)f.onFullScreen(lb);if(f.onFullscreen)f.onFullscreen(lb)}Bb=a;R=b;"undefined"===typeof Bb&&(Bb=!0);"undefined"===typeof R&&(R=!1);var d=f.canvas;Ab||(Ab=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Db(){if(!lb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Gb=0;function Hb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Gb)Gb=b+1E3/60;else for(;b+2>=Gb;)Gb+=1E3/60;setTimeout(a,Math.max(Gb-b,0))}}function ub(a){noExitRuntime=!0;setTimeout(function(){C||a()},1E4)}
function tb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ib=[];function Fb(){var a=f.canvas;Ib.forEach(function(b){b(a.width,a.height)})}
function Eb(a,b,c){b&&c?(a.Cb=b,a.zb=c):(b=a.Cb,c=a.zb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}R?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var pb,qb,rb,sb;
function Jb(a,b){db=a;eb=b;if(bb)if(0==a)O=function(){var d=Math.max(0,jb+b-Kb())|0;setTimeout(kb,d)};else if(1==a)O=function(){Hb(kb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);t?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}O=function(){setImmediate(kb)}}}var Kb;ba?Kb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Kb=dateNow:Kb=function(){return performance.now()};
function Lb(a,b,c,d,e){noExitRuntime=!0;assert(!bb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");bb=a;cb=d;var g=P;kb=function(){if(!C)if(0<gb.length){var h=Date.now(),m=gb.shift();m.ub(m.jb);if(ib){var n=ib,p=0==n%1?n-1:Math.floor(n);ib=m.Fb?p:(8*n+(p+.5))/9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||
"Please wait...",m=ib,n=hb.Jb,m?m<n?f.setStatus(h+" ("+(n-m)+"/"+n+")"):f.setStatus(h):f.setStatus(""));g<P||setTimeout(kb,0)}else if(!(g<P))if(fb=fb+1|0,1==db&&1<eb&&0!=fb%eb)O();else{0==db&&(jb=Kb());a:if(!(C||f.preMainLoop&&!1===f.preMainLoop())){try{a()}catch(r){if(r instanceof ha||"unwind"==r)break a;r&&"object"===typeof r&&r.stack&&x("exception thrown: "+[r,r.stack]);throw r;}f.postMainLoop&&f.postMainLoop()}g<P||("object"===typeof SDL&&SDL.audio&&SDL.audio.Bb&&SDL.audio.Bb(),O())}};e||(b&&
0<b?Jb(0,1E3/b):Jb(1,1),O());if(c)throw"unwind";}function Mb(a,b,c){a>>=2;G[a]=b.screenX;G[a+1]=b.screenY;G[a+2]=b.clientX;G[a+3]=b.clientY;G[a+4]=b.ctrlKey;G[a+5]=b.shiftKey;G[a+6]=b.altKey;G[a+7]=b.metaKey;qa[2*a+16]=b.button;qa[2*a+17]=b.buttons;G[a+9]=b.movementX;G[a+10]=b.movementY;c=$a(c);G[a+11]=b.clientX-c.left;G[a+12]=b.clientY-c.top}
function Nb(a,b,c,d,e,g){Wa||(Wa=N(64));a=M(a);Sa({target:a,ob:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,fb:g,kb:d,mb:function(h){h=h||event;Mb(Wa,h,a);A.get(d)(e,Wa,b)&&h.preventDefault()},ib:c})}
function Ob(a,b,c,d){Xa||(Xa=N(36));a=M(a);Sa({target:a,fb:"resize",kb:d,mb:function(e){e=e||event;if(e.target==a){var g=Xa,h=document.body;G[g>>2]=e.detail;G[g+4>>2]=h.clientWidth;G[g+8>>2]=h.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;A.get(d)(10,g,b)&&e.preventDefault()}},ib:c})}
function Pb(a,b,c,d){Ya||(Ya=N(96));Sa({target:a,ob:!0,fb:"wheel",kb:d,mb:function(e){e=e||event;var g=Ya;Mb(g,e,a);I[g+64>>3]=e.deltaX;I[g+72>>3]=e.deltaY;I[g+80>>3]=e.deltaZ;G[g+88>>2]=e.deltaMode;A.get(d)(9,g,b)&&e.preventDefault()},ib:c})}
function Qb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Rb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Sb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Tb=1,Ub=[],T=[],Vb=[],Wb=[],Xb=[],U=[],V=[],yb=[],Yb={},Zb={},$b=4;
function W(a){ac||(ac=a)}function X(a){for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b}function xb(a,b){if(a=1<b.qb?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=X(yb),d={Lb:c,attributes:b,version:b.qb,nb:a};a.canvas&&(a.canvas.Db=d);yb[c]=d;("undefined"===typeof b.tb||b.tb)&&cc(d);b=c}else b=0;return b}function zb(a){Y=yb[a];f.pb=Q=Y&&Y.nb;return!(a&&!Q)}
function cc(a){a||(a=Y);if(!a.Ab){a.Ab=!0;var b=a.nb;Qb(b);Rb(b);Sb(b);b.Gb=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Hb=b.getExtension("EXT_disjoint_timer_query");b.Nb=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var wb={},ac,Y,dc=["default","low-power","high-performance"];function ec(a,b,c,d){for(var e=0;e<a;e++){var g=Q[c](),h=g&&X(d);g?(g.name=h,d[h]=g):W(1282);G[b+4*e>>2]=h}}
function fc(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W(1282);return}c=2*(Q.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>Y.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else W(1281)}
function hc(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b+=1;c=N(b);F(a,c,b);return c}function ic(a){a-=5120;return 0==a?pa:1==a?E:2==a?qa:4==a?G:6==a?H:5==a||28922==a||28520==a||30779==a||30782==a?sa:ra}
function jc(a,b,c,d,e){a=ic(a);var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=$b;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var Z=[];f.requestFullscreen=function(a,b){Cb(a,b)};f.requestAnimationFrame=function(a){Hb(a)};f.setCanvasSize=function(a,b,c){Eb(f.canvas,a,b);c||Fb()};f.pauseMainLoop=function(){O=null;P++};f.resumeMainLoop=function(){P++;var a=db,b=eb,c=bb;bb=null;Lb(c,0,!1,cb,!0);Jb(a,b);O()};
f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return vb(a,b,c,d)};for(var Q,kc=new Float32Array(288),lc=0;288>lc;++lc)Z[lc]=kc.subarray(0,lc+1);
var qc={b:A,R:function(){return 0},na:function(){return 0},oa:function(){},j:function(){w()},ea:function(a,b,c){a=M(a);if(!a)return-4;a=$a(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},ka:function(a,b,c){E.copyWithin(a,b,b+c)},la:function(a){a>>>=0;var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{z.grow(Math.min(2147483648,d)-oa.byteLength+65535>>>16);ta(z.buffer);var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},ba:function(a,b,c){a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},za:function(a,b,c,d){ab(a,b,c,d,2,"keydown");return 0},xa:function(a,b,c,d){ab(a,b,c,d,1,"keypress");return 0},ya:function(a,b,c,d){ab(a,b,c,d,3,"keyup");return 0},ra:function(a,b,c,d,e){Lb(function(){A.get(a)()},b,c,d,e)},wa:function(a,b,c,d){Nb(a,b,c,d,5,"mousedown");return 0},ua:function(a,b,c,d){Nb(a,b,c,d,33,"mouseenter");return 0},ta:function(a,b,c,d){Nb(a,b,c,d,34,"mouseleave");return 0},
sa:function(a,b,c,d){Nb(a,b,c,d,8,"mousemove");return 0},va:function(a,b,c,d){Nb(a,b,c,d,6,"mouseup");return 0},Ra:function(a,b,c,d){Ob(a,b,c,d);return 0},qa:function(a,b,c,d){a=M(a);return"undefined"!==typeof a.onwheel?(Pb(a,b,c,d),0):-1},U:function(a,b){var c={};b>>=2;c.alpha=!!G[b];c.depth=!!G[b+1];c.stencil=!!G[b+2];c.antialias=!!G[b+3];c.premultipliedAlpha=!!G[b+4];c.preserveDrawingBuffer=!!G[b+5];c.powerPreference=dc[G[b+6]];c.failIfMajorPerformanceCaveat=!!G[b+7];c.qb=G[b+8];c.Mb=G[b+9];c.tb=
G[b+10];c.yb=G[b+11];c.Pb=G[b+12];c.Qb=G[b+13];a=M(a);return!a||c.yb?0:xb(a,c)},Na:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},Ba:function(a){return zb(a)?0:-5},S:function(){return 0},ma:function(a,b,c,d){a=La.Kb(a);b=La.Ib(a,b,c);G[d>>2]=b;return 0},Va:function(){},Q:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var h=G[b+8*g>>2],m=G[b+(8*g+4)>>2],n=0;n<m;n++){var p=E[h+n],r=Ka[a];0===p||10===p?((1===a?ja:x)(na(r,0)),r.length=0):r.push(p)}e+=m}G[d>>
2]=e;return 0},o:function(a){Q.activeTexture(a)},w:function(a,b){Q.attachShader(T[a],V[b])},T:function(a,b,c){Q.bindAttribLocation(T[a],b,D(c))},e:function(a,b){35051==a?Q.sb=b:35052==a&&(Q.lb=b);Q.bindBuffer(a,Ub[b])},Z:function(a,b){Q.bindFramebuffer(a,Vb[b])},Ta:function(a,b){Q.bindRenderbuffer(a,Wb[b])},c:function(a,b){Q.bindTexture(a,Xb[b])},ga:function(a,b,c,d){Q.blendColor(a,b,c,d)},ha:function(a,b){Q.blendEquationSeparate(a,b)},N:function(a,b,c,d){Q.blendFuncSeparate(a,b,c,d)},J:function(a,
b,c,d){2<=Y.version?c?Q.bufferData(a,E,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?E.subarray(c,c+b):b,d)},y:function(a,b,c,d){2<=Y.version?Q.bufferSubData(a,b,E,d,c):Q.bufferSubData(a,b,E.subarray(d,d+c))},Ja:function(a){Q.clear(a)},Ma:function(a,b,c,d){Q.clearColor(a,b,c,d)},La:function(a){Q.clearDepth(a)},Ka:function(a){Q.clearStencil(a)},k:function(a,b,c,d){Q.colorMask(!!a,!!b,!!c,!!d)},E:function(a){Q.compileShader(V[a])},ca:function(){var a=X(T),b=Q.createProgram();b.name=a;T[a]=b;return a},
G:function(a){var b=X(V);V[b]=Q.createShader(a);return b},L:function(a){Q.cullFace(a)},Pa:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=Ub[d];e&&(Q.deleteBuffer(e),e.name=0,Ub[d]=null,d==Q.sb&&(Q.sb=0),d==Q.lb&&(Q.lb=0))}},_:function(a){if(a){var b=T[a];b?(Q.deleteProgram(b),b.name=0,T[a]=null,Yb[a]=null):W(1281)}},s:function(a){if(a){var b=V[a];b?(Q.deleteShader(b),V[a]=null):W(1281)}},Y:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=Xb[d];e&&(Q.deleteTexture(e),e.name=0,Xb[d]=null)}},
P:function(a){Q.depthFunc(a)},O:function(a){Q.depthMask(!!a)},d:function(a){Q.disable(a)},z:function(a){Q.disableVertexAttribArray(a)},h:function(a,b,c){Q.drawArrays(a,b,c)},Fa:function(a,b,c,d){Q.drawElements(a,b,c,d)},g:function(a){Q.enable(a)},B:function(a){Q.enableVertexAttribArray(a)},Ca:function(){Q.finish()},M:function(a){Q.frontFace(a)},K:function(a,b){ec(a,b,"createBuffer",Ub)},Ua:function(a,b){ec(a,b,"createRenderbuffer",Wb)},da:function(a,b){ec(a,b,"createTexture",Xb)},Aa:function(a){Q.generateMipmap(a)},
Qa:function(a,b){return Q.getAttribLocation(T[a],D(b))},f:function(){var a=Q.getError()||ac;ac=0;return a},m:function(a,b){fc(a,b)},$:function(a,b,c,d){a=Q.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(G[c>>2]=b)},I:function(a,b,c){if(c)if(a>=Tb)W(1281);else{var d=Yb[a];if(d)if(35716==b)a=Q.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==b)G[c>>2]=d.rb;else if(35722==b){if(-1==d.gb){a=T[a];var e=Q.getProgramParameter(a,35721);
for(b=d.gb=0;b<e;++b)d.gb=Math.max(d.gb,Q.getActiveAttrib(a,b).name.length+1)}G[c>>2]=d.gb}else if(35381==b){if(-1==d.hb)for(a=T[a],e=Q.getProgramParameter(a,35382),b=d.hb=0;b<e;++b)d.hb=Math.max(d.hb,Q.getActiveUniformBlockName(a,b).length+1);G[c>>2]=d.hb}else G[c>>2]=Q.getProgramParameter(T[a],b);else W(1282)}else W(1281)},D:function(a,b,c,d){a=Q.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(G[c>>2]=b)},v:function(a,b,c){c?35716==b?(a=Q.getShaderInfoLog(V[a]),null===
a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(V[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=Q.getShaderParameter(V[a],b):W(1281)},Wa:function(a){if(Zb[a])return Zb[a];switch(a){case 7939:var b=Q.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=hc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||W(1280);b=hc(b);break;case 7938:b=Q.getParameter(7938);b=2<=Y.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";
b=hc(b);break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=hc(b);break;default:return W(1280),0}return Zb[a]=b},n:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Yb[a]&&Yb[a].wb[b])&&0<=c&&c<a[0]?a[1]+c:-1},aa:function(a){Q.linkProgram(T[a]);var b=T[a];a=Yb[a]={wb:{},rb:0,gb:-1,
hb:-1};for(var c=a.wb,d=Q.getProgramParameter(b,35718),e=0;e<d;++e){var g=Q.getActiveUniform(b,e),h=g.name;a.rb=Math.max(a.rb,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=Q.getUniformLocation(b,h);if(m){var n=X(U);c[h]=[g.size,n];U[n]=m;for(var p=1;p<g.size;++p)m=Q.getUniformLocation(b,h+"["+p+"]"),n=X(U),U[n]=m}}},t:function(a,b){3317==a&&($b=b);Q.pixelStorei(a,b)},fa:function(a,b){Q.polygonOffset(a,b)},Sa:function(a,b,c,d){Q.renderbufferStorage(a,b,c,d)},X:function(a,b,
c,d){Q.scissor(a,b,c,d)},F:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?G[d+4*g>>2]:-1;e+=D(G[c+4*g>>2],0>h?void 0:h)}Q.shaderSource(V[a],e)},l:function(a,b,c){Q.stencilFunc(a,b,c)},W:function(a,b,c,d){Q.stencilFuncSeparate(a,b,c,d)},q:function(a){Q.stencilMask(a)},p:function(a,b,c){Q.stencilOp(a,b,c)},u:function(a,b,c,d){Q.stencilOpSeparate(a,b,c,d)},x:function(a,b,c,d,e,g,h,m,n){if(2<=Y.version)if(Q.lb)Q.texImage2D(a,b,c,d,e,g,h,m,n);else if(n){var p=ic(m);Q.texImage2D(a,b,c,d,e,g,h,m,p,
n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else Q.texImage2D(a,b,c,d,e,g,h,m,null);else Q.texImage2D(a,b,c,d,e,g,h,m,n?jc(m,h,d,e,n):null)},i:function(a,b,c){Q.texParameteri(a,b,c)},Ea:function(a,b,c,d,e,g,h,m,n){if(2<=Y.version)if(Q.lb)Q.texSubImage2D(a,b,c,d,e,g,h,m,n);else if(n){var p=ic(m);Q.texSubImage2D(a,b,c,d,e,g,h,m,p,n>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else Q.texSubImage2D(a,b,c,d,e,g,h,m,null);else p=null,n&&(p=jc(m,h,e,g,n)),Q.texSubImage2D(a,b,c,d,e,g,h,m,p)},Ia:function(a,b,c){if(2<=
Y.version)Q.uniform1fv(U[a],H,c>>2,b);else{if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=H[c+4*e>>2];else d=H.subarray(c>>2,c+4*b>>2);Q.uniform1fv(U[a],d)}},H:function(a,b){Q.uniform1i(U[a],b)},V:function(a,b,c){if(2<=Y.version)Q.uniform2fv(U[a],H,c>>2,2*b);else{if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);Q.uniform2fv(U[a],d)}},Ha:function(a,b,c){if(2<=Y.version)Q.uniform3fv(U[a],H,c>>2,3*b);else{if(96>=b)for(var d=Z[3*b-1],e=
0;e<3*b;e+=3)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2],d[e+2]=H[c+(4*e+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);Q.uniform3fv(U[a],d)}},A:function(a,b,c){if(2<=Y.version)Q.uniform4fv(U[a],H,c>>2,4*b);else{if(72>=b){var d=Z[4*b-1],e=H;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=H.subarray(c>>2,c+16*b>>2);Q.uniform4fv(U[a],d)}},Ga:function(a,b,c,d){if(2<=Y.version)Q.uniformMatrix4fv(U[a],!!c,H,d>>2,16*b);else{if(18>=b){var e=Z[16*b-1],g=H;d>>=2;for(var h=
0;h<16*b;h+=16){var m=d+h;e[h]=g[m];e[h+1]=g[m+1];e[h+2]=g[m+2];e[h+3]=g[m+3];e[h+4]=g[m+4];e[h+5]=g[m+5];e[h+6]=g[m+6];e[h+7]=g[m+7];e[h+8]=g[m+8];e[h+9]=g[m+9];e[h+10]=g[m+10];e[h+11]=g[m+11];e[h+12]=g[m+12];e[h+13]=g[m+13];e[h+14]=g[m+14];e[h+15]=g[m+15]}}else e=H.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(U[a],!!c,e)}},r:function(a){Q.useProgram(T[a])},pa:function(a,b){Q.vertexAttribDivisor(a,b)},C:function(a,b,c,d,e,g){Q.vertexAttribPointer(a,b,c,!!d,e,g)},Oa:function(a,b,c,d){Q.viewport(a,
b,c,d)},a:z,ja:function(a,b,c,d,e,g){b=D(b);var h=new XMLHttpRequest;h.open("GET",b);h.responseType="arraybuffer";var m=0<d;m&&h.setRequestHeader("Range","bytes="+c+"-"+(c+d));h.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var n=new Uint8Array(h.response),p=n.length;p<=g?(E.set(n,e),mc(a,d,p)):nc(a)}else oc(a,this.status)};h.send()},Da:function(a,b){b=D(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==
this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");pc(a,d)}else oc(a,this.status)};c.send()},ia:function(){return performance.now()}};
(function(){function a(e){f.asm=e.exports;J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Ba&&(clearInterval(Ba),Ba=null),Ca&&(e=Ca,Ca=null,e()))}function b(e){a(e.instance)}function c(e){return Ha().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){x("failed to asynchronously prepare wasm: "+g);w(g)})}var d={a:qc};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(y||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||Da("file://")||"function"!==typeof fetch)return c(b);fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){x("wasm streaming compile failed: "+g);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Ia=f.___wasm_call_ctors=function(){return(Ia=f.___wasm_call_ctors=f.asm.Xa).apply(null,arguments)};
f.___em_js__sfetch_js_send_head_request=function(){return(f.___em_js__sfetch_js_send_head_request=f.asm.Ya).apply(null,arguments)};f.___em_js__sfetch_js_send_get_request=function(){return(f.___em_js__sfetch_js_send_get_request=f.asm.Za).apply(null,arguments)};
var pc=f.__sfetch_emsc_head_response=function(){return(pc=f.__sfetch_emsc_head_response=f.asm._a).apply(null,arguments)},mc=f.__sfetch_emsc_get_response=function(){return(mc=f.__sfetch_emsc_get_response=f.asm.$a).apply(null,arguments)},oc=f.__sfetch_emsc_failed_http_status=function(){return(oc=f.__sfetch_emsc_failed_http_status=f.asm.ab).apply(null,arguments)},nc=f.__sfetch_emsc_failed_buffer_too_small=function(){return(nc=f.__sfetch_emsc_failed_buffer_too_small=f.asm.bb).apply(null,arguments)};
f.___em_js__stm_js_perfnow=function(){return(f.___em_js__stm_js_perfnow=f.asm.cb).apply(null,arguments)};var N=f._malloc=function(){return(N=f._malloc=f.asm.db).apply(null,arguments)};f._main=function(){return(f._main=f.asm.eb).apply(null,arguments)};var rc;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ca=function sc(){rc||tc();rc||(Ca=sc)};
function tc(){function a(){if(!rc&&(rc=!0,f.calledRun=!0,!C)){Ja(wa);Ja(xa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(uc){var b=f._main;try{var c=b(0,0);if(!noExitRuntime||0!==c){if(!noExitRuntime){if(f.onExit)f.onExit(c);C=!0}q(c,new ha(c))}}catch(d){d instanceof ha||("unwind"==d?noExitRuntime=!0:((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),x("exception thrown: "+b),q(1,d)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=
f.postRun.shift(),za.unshift(b);Ja(za)}}if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();Ja(va);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=tc;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var uc=!0;f.noInitialRun&&(uc=!1);noExitRuntime=!0;tc();
