var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=Object.assign({},h),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja,ka;
if(ca){var fs=require("fs"),ma=require("path");k=__dirname+"/";ia=(a,b)=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a};ja=(a,b,c)=>{a=na(a)?new URL(a):ma.normalize(a);fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof oa||a.context instanceof oa))throw a;});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ja=(a,b,c)=>{if(na(a)){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)}else fetch(a,{credentials:"same-origin"}).then(e=>e.ok?e.arrayBuffer():Promise.reject(Error(e.status+" : "+e.url))).then(b,c)};var pa=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);
h.quit&&(ha=h.quit);var r;h.wasmBinary&&(r=h.wasmBinary);var qa,x=!1,ra,sa,y,ta,ua,z,A,B,C;function va(){var a=qa.buffer;h.HEAP8=sa=new Int8Array(a);h.HEAP16=ta=new Int16Array(a);h.HEAPU8=y=new Uint8Array(a);h.HEAPU16=ua=new Uint16Array(a);h.HEAP32=z=new Int32Array(a);h.HEAPU32=A=new Uint32Array(a);h.HEAPF32=B=new Float32Array(a);h.HEAPF64=C=new Float64Array(a)}var wa=[],xa=[],ya=[],za=[];function Aa(){var a=h.preRun.shift();wa.unshift(a)}var D=0,Ba=null,Ca=null;
function Da(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);x=!0;ra=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ea=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Fa;function Ga(a){if(a==Fa&&r)return new Uint8Array(r);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}
function Ha(a){return r?Promise.resolve().then(()=>Ga(a)):new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),()=>{try{b(Ga(a))}catch(d){c(d)}})})}function Ia(a,b,c){return Ha(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);Da(d)})}
function Ja(a,b){var c=Fa;r||"function"!=typeof WebAssembly.instantiateStreaming||Ea(c)||na(c)||ca||"function"!=typeof fetch?Ia(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return Ia(c,a,b)}))}var E;function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ka=a=>{for(;0<a.length;)a.shift()(h)},La=h.noExitRuntime||!0,Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Na=a=>0===a%4&&(0!==a%100||0===a%400),Oa=[0,31,60,91,121,152,182,213,244,274,305,335],Pa=[0,31,59,90,120,151,181,212,243,273,304,334],G=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var n=a.charCodeAt(++g);f=65536+((f&1023)<<10)|n&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|
f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0;return c-e},Za=(a,b)=>{Qa=a;Ra=b;if(Sa)if(Ta||=!0,0==a)H=function(){var d=Math.max(0,Ua+b-Va())|0;setTimeout(Wa,d)};else if(1==a)H=function(){Xa(Wa)};else if(2==a){if("undefined"==typeof Ya)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ya=function(d){c.push(d);ba?(void 0===
h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Ya=setImmediate;H=function(){Ya(Wa)}}},Va;Va=()=>performance.now();
var gb=(a,b,c,d,e)=>{Sa=a;$a=d;var g=I;Ta=!1;Wa=function(){if(!x)if(0<ab.length){var f=ab.shift();f.td(f.od);if(bb){var n=bb,p=0==n%1?n-1:Math.floor(n);bb=f.qd?p:(8*n+(p+.5))/9}h.setStatus&&(f=h.statusMessage||"Please wait...",n=bb,p=cb.sd,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(f):h.setStatus(""));g<I||setTimeout(Wa,0)}else if(!(g<I))if(db=db+1|0,1==Qa&&1<Ra&&0!=db%Ra)H();else{0==Qa&&(Ua=Va());if(!(x||h.preMainLoop&&!1===h.preMainLoop())){if(!x)try{if(a(),!La)try{ra=
f=ra,eb(f)}catch(q){fb(q)}}catch(q){fb(q)}h.postMainLoop?.()}g<I||("object"==typeof SDL&&SDL.audio?.xd?.(),H())}};e||(b&&0<b?Za(0,1E3/b):Za(1,1),H());if(c)throw"unwind";},fb=a=>{a instanceof oa||"unwind"==a||ha(1,a)},eb=a=>{ra=a;La||(h.onExit?.(a),x=!0);ha(a,new oa(a))},hb=a=>{ra=a;eb(a)},Ta=!1,H=null,I=0,Sa=null,$a=0,Qa=0,Ra=0,db=0,ab=[];function ib(){H=null;I++}var cb={},Ua,Wa,bb,jb=!1,kb=!1,lb=[];
function mb(){function a(){kb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!nb){nb=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!kb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var ob=!1,pb=void 0,J=void 0;
function qb(){if(!jb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var rb=0;function Xa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===rb)rb=b+1E3/60;else for(;b+2>=rb;)rb+=1E3/60;setTimeout(a,Math.max(rb-b,0))}}var sb=[];function tb(){var a=h.canvas;sb.forEach(b=>b(a.width,a.height))}
function ub(a,b,c){b&&c?(a.md=b,a.dd=c):(b=a.md,c=a.dd);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ya,nb,vb=0,wb=[];
function xb(){if(navigator.userActivation?navigator.userActivation.isActive:vb&&yb.Hc)for(var a=0;a<wb.length;++a){var b=wb[a];wb.splice(a,1);--a;b.Bd(...b.pd)}}var K=[];function zb(a){var b=K[a];b.target.removeEventListener(b.qc,b.Pc,b.sc);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.tc)a.Pc=function(c){++vb;yb=a;xb();a.uc(c);xb();--vb},a.target.addEventListener(a.qc,a.Pc,a.sc),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].qc==a.qc&&zb(b--);return 0}
function Ab(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var yb,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?F(y,a):"":a;return Ib[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Jb=a=>0>Ib.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Kb=[],Lb,N=a=>{var b=Kb[a];b||(a>=Kb.length&&(Kb.length=a+1),Kb[a]=b=Lb.get(a));return b},Mb=(a,b,c,d,e,g)=>{Bb||=O(256);a={target:M(a),qc:g,tc:d,uc:(f=event)=>{var n=f.target.id?f.target.id:"",p=Bb;G(Ab(f.target),y,p+0,128);
G(n,y,p+128,128);N(d)(e,p,b)&&f.preventDefault()},sc:c};return L(a)},Nb=(a,b,c,d,e,g)=>{Cb||=O(176);a={target:M(a),qc:g,tc:d,uc:f=>{var n=Cb;C[n>>3]=f.timeStamp;var p=n>>2;z[p+2]=f.location;z[p+3]=f.ctrlKey;z[p+4]=f.shiftKey;z[p+5]=f.altKey;z[p+6]=f.metaKey;z[p+7]=f.repeat;z[p+8]=f.charCode;z[p+9]=f.keyCode;z[p+10]=f.which;G(f.key||"",y,n+44,32);G(f.code||"",y,n+76,32);G(f.char||"",y,n+108,32);G(f.locale||"",y,n+140,32);N(d)(e,n,b)&&f.preventDefault()},sc:c};return L(a)},Ob=(a,b,c)=>{C[a>>3]=b.timeStamp;
a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=b.altKey;z[a+9]=b.metaKey;ta[2*a+20]=b.button;ta[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=Jb(c);z[a+13]=b.clientX-(c.left|0);z[a+14]=b.clientY-(c.top|0)},Pb=(a,b,c,d,e,g)=>{Db||=O(72);a=M(a);return L({target:a,Hc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,qc:g,tc:d,uc:(f=event)=>{Ob(Db,f,a);N(d)(e,Db,b)&&f.preventDefault()},sc:c})},Qb=(a,b,c,d,e)=>{Eb||=O(260);
return L({target:a,qc:e,tc:d,uc:(g=event)=>{var f=Eb,n=document.pointerLockElement||document.zc||document.Tc||document.Sc;z[f>>2]=!!n;var p=n?.id||"";G(Ab(n),y,f+4,128);G(p,y,f+132,128);N(d)(20,f,b)&&g.preventDefault()},sc:c})},Rb=(a,b,c,d,e)=>L({target:a,qc:e,tc:d,uc:(g=event)=>{N(d)(38,0,b)&&g.preventDefault()},sc:c}),Sb=(a,b,c,d)=>{Fb||=O(36);a=M(a);return L({target:a,qc:"resize",tc:d,uc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=Fb;z[f>>2]=0;z[f+4>>2]=g.clientWidth;z[f+8>>2]=
g.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset|0;z[f+32>>2]=pageYOffset|0;N(d)(10,f,b)&&e.preventDefault()}}},sc:c})},Tb=(a,b,c,d,e,g)=>{Gb||=O(1696);a=M(a);return L({target:a,Hc:"touchstart"==g||"touchend"==g,qc:g,tc:d,uc:f=>{for(var n,p={},q=f.touches,t=0;t<q.length;++t)n=q[t],n.Qc=n.Rc=0,p[n.identifier]=n;for(t=0;t<f.changedTouches.length;++t)n=f.changedTouches[t],n.Qc=1,p[n.identifier]=n;for(t=0;t<f.targetTouches.length;++t)p[f.targetTouches[t].identifier].Rc=
1;q=Gb;C[q>>3]=f.timeStamp;var v=q>>2;z[v+3]=f.ctrlKey;z[v+4]=f.shiftKey;z[v+5]=f.altKey;z[v+6]=f.metaKey;v+=7;var la=Jb(a),m=0;for(t in p)if(n=p[t],z[v]=n.identifier,z[v+1]=n.screenX,z[v+2]=n.screenY,z[v+3]=n.clientX,z[v+4]=n.clientY,z[v+5]=n.pageX,z[v+6]=n.pageY,z[v+7]=n.Qc,z[v+8]=n.Rc,z[v+9]=n.clientX-(la.left|0),z[v+10]=n.clientY-(la.top|0),v+=13,31<++m)break;z[q+8>>2]=m;N(d)(e,q,b)&&f.preventDefault()},sc:c})},Ub=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,
d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Vb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Wb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>
b.drawBuffersWEBGL(c,d))},Xb=a=>{a.rd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Yb=a=>{a.ud=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Zb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},$b=1,ac=[],P=[],bc=[],cc=[],dc=[],Q=[],ec=[],fc=[],S=[],gc={},hc=4,ic=0,jc=a=>{for(var b=$b++,c=a.length;c<b;c++)a[c]=null;return b},kc=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=T[c](),f=g&&jc(d);g?(g.name=f,d[f]=g):U||=1282;z[b+4*e>>2]=f}},mc=(a,b)=>{a.zc||(a.zc=a.getContext,a.getContext=function(d,e){e=a.zc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Jc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?lc(c,b):0},lc=(a,b)=>{var c=jc(fc),d={handle:c,attributes:b,version:b.Jc,Bc:a};a.canvas&&(a.canvas.nd=d);fc[c]=d;("undefined"==typeof b.Oc||b.Oc)&&nc(d);return c},pc=a=>{V=fc[a];h.Ic=T=V?.Bc;return!(a&&!T)},nc=a=>{a||=V;if(!a.ed){a.ed=!0;var b=a.Bc;Ub(b);Vb(b);Wb(b);Xb(b);Yb(b);2<=a.version&&(b.Nc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Nc)b.Nc=b.getExtension("EXT_disjoint_timer_query");b.gd=b.getExtension("WEBGL_multi_draw");Zb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},qc={},U,V,rc=(a,b,c,d,e,g)=>{a={target:M(a),qc:g,tc:d,uc:(f=event)=>{N(d)(e,0,b)&&f.preventDefault()},sc:c};L(a)},sc=(a,b,c,d)=>{Hb||=O(104);return L({target:a,Hc:!0,qc:"wheel",tc:d,uc:(e=event)=>{var g=Hb;Ob(g,e,a);C[g+72>>3]=e.deltaX;C[g+80>>3]=e.deltaY;C[g+88>>3]=e.deltaZ;z[g+96>>2]=e.deltaMode;N(d)(9,g,b)&&e.preventDefault()},sc:c})},tc=["default","low-power","high-performance"],uc={},wc=()=>{if(!vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in uc)void 0===uc[b]?delete a[b]:a[b]=uc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);vc=c}return vc},vc,xc=[null,[],[]];function yc(){var a=Zb(T);return a=a.concat(a.map(b=>"GL_"+b))}
var zc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=yc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}z[b>>2]=c}else U||=1281},Ac=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Bc=a=>{var b=Ac(a)+1,c=O(b);c&&G(a,y,c,b);return c},Cc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Dc=[],Ec=a=>{a-=5120;return 0==a?sa:1==a?y:2==a?ta:4==a?z:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?A:ua},Fc=(a,b,c,d,e)=>{a=Ec(a);b=d*((ic||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+hc-1&-hc);return a.subarray(e>>>
31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=T.bd;if(b){var c=b.Ac[a];"number"==typeof c&&(b.Ac[a]=c=T.getUniformLocation(b,b.$c[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Gc=[],Hc=[31,29,31,30,31,30,31,31,30,31,30,31],Ic=[31,28,31,30,31,30,31,31,30,31,30,31];function Jc(a){var b=Array(Ac(a)+1);G(a,b,0,b.length);return b}
var Kc=(a,b,c,d)=>{function e(m,u,w){for(m="number"==typeof m?m.toString():m||"";m.length<u;)m=w[0]+m;return m}function g(m,u){return e(m,u,"0")}function f(m,u){function w(oc){return 0>oc?-1:0<oc?1:0}var R;0===(R=w(m.getFullYear()-u.getFullYear()))&&0===(R=w(m.getMonth()-u.getMonth()))&&(R=w(m.getDate()-u.getDate()));return R}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){var u=m.xc;for(m=new Date((new Date(m.yc+1900,0,1)).getTime());0<u;){var w=m.getMonth(),R=(Na(m.getFullYear())?Hc:Ic)[w];if(u>R-m.getDate())u-=R-m.getDate()+1,m.setDate(1),11>w?m.setMonth(w+1):(m.setMonth(0),m.setFullYear(m.getFullYear()+1));else{m.setDate(m.getDate()+u);break}}w=new Date(m.getFullYear()+1,0,4);u=n(new Date(m.getFullYear(),
0,4));w=n(w);return 0>=f(u,m)?0>=f(w,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var q=A[d+40>>2];d={kd:z[d>>2],jd:z[d+4>>2],Fc:z[d+8>>2],Kc:z[d+12>>2],Gc:z[d+16>>2],yc:z[d+20>>2],rc:z[d+24>>2],xc:z[d+28>>2],Cd:z[d+32>>2],hd:z[d+36>>2],ld:q?q?F(y,q):"":""};c=c?F(y,c):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in q)c=c.replace(new RegExp(t,"g"),q[t]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),la="January February March April May June July August September October November December".split(" ");q={"%a":m=>v[m.rc].substring(0,3),"%A":m=>v[m.rc],"%b":m=>la[m.Gc].substring(0,3),"%B":m=>la[m.Gc],"%C":m=>g((m.yc+1900)/
100|0,2),"%d":m=>g(m.Kc,2),"%e":m=>e(m.Kc,2," "),"%g":m=>p(m).toString().substring(2),"%G":p,"%H":m=>g(m.Fc,2),"%I":m=>{m=m.Fc;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":m=>{for(var u=0,w=0;w<=m.Gc-1;u+=(Na(m.yc+1900)?Hc:Ic)[w++]);return g(m.Kc+u,3)},"%m":m=>g(m.Gc+1,2),"%M":m=>g(m.jd,2),"%n":()=>"\n","%p":m=>0<=m.Fc&&12>m.Fc?"AM":"PM","%S":m=>g(m.kd,2),"%t":()=>"\t","%u":m=>m.rc||7,"%U":m=>g(Math.floor((m.xc+7-m.rc)/7),2),"%V":m=>{var u=Math.floor((m.xc+7-(m.rc+6)%7)/7);2>=(m.rc+371-m.xc-2)%7&&
u++;if(u)53==u&&(w=(m.rc+371-m.xc)%7,4==w||3==w&&Na(m.yc)||(u=1));else{u=52;var w=(m.rc+7-m.xc-1)%7;(4==w||5==w&&Na(m.yc%400-1))&&u++}return g(u,2)},"%w":m=>m.rc,"%W":m=>g(Math.floor((m.xc+7-(m.rc+6)%7)/7),2),"%y":m=>(m.yc+1900).toString().substring(2),"%Y":m=>m.yc+1900,"%z":m=>{m=m.hd;var u=0<=m;m=Math.abs(m)/60;return(u?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":m=>m.ld,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(t in q)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),q[t](d)));c=
c.replace(/\0\0/g,"%");t=Jc(c);if(t.length>b)return 0;sa.set(t,a);return t.length-1},Mc=a=>{var b=Ac(a)+1,c=Lc(b);G(a,y,c,b);return c},Pc=a=>{var b=Nc();a();Oc(b)};
h.requestFullscreen=function(a,b){function c(){jb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=qb,pb&&d.requestPointerLock(),jb=!0,J?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=A[SDL.screen>>2]|8388608),ub(h.canvas),tb()):ub(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),J?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=A[SDL.screen>>
2]&-8388609),ub(h.canvas),tb()):ub(d));h.onFullScreen?.(jb);h.onFullscreen?.(jb)}pb=a;J=b;"undefined"==typeof pb&&(pb=!0);"undefined"==typeof J&&(J=!1);var d=h.canvas;ob||(ob=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Xa;h.setCanvasSize=function(a,b,c){ub(h.canvas,a,b);c||tb()};h.pauseMainLoop=ib;h.resumeMainLoop=function(){I++;var a=Qa,b=Ra,c=Sa;Sa=null;gb(c,0,!1,$a,!0);Za(a,b);H()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.Ic&&a==h.canvas)return h.Ic;var e;if(b){var g={antialias:!1,alpha:!1,Jc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof qc&&(e=mc(a,g)))var n=fc[e].Bc}else n=a.getContext("2d");if(!n)return null;c&&(h.Ic=n,b&&pc(e),h.Dd=b,lb.forEach(p=>p()),mb());return n};
for(var T,Y=0;32>Y;++Y)Dc.push(Array(Y));var Qc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Qc.subarray(0,Y);var Rc=new Int32Array(288);for(Y=0;288>Y;++Y)Gc[Y]=Rc.subarray(0,Y);
var bd={Ia:function(){return 0},zb:function(){return 0},Ab:function(){},vb:()=>{},Cb:()=>{Da("")},Bb:()=>1,wb:(a,b,c)=>y.copyWithin(a,b,b+c),nb:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));z[c>>2]=a.getUTCSeconds();z[c+4>>2]=a.getUTCMinutes();z[c+8>>2]=a.getUTCHours();z[c+12>>2]=a.getUTCDate();z[c+16>>2]=a.getUTCMonth();z[c+20>>2]=a.getUTCFullYear()-1900;z[c+24>>2]=a.getUTCDay();z[c+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},ob:function(a){var b=
new Date(z[a+20>>2]+1900,z[a+16>>2],z[a+12>>2],z[a+8>>2],z[a+4>>2],z[a>>2],0),c=z[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),f=Math.min(g,e);0>c?z[a+32>>2]=Number(e!=g&&f==d):0<c!=(f==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?f:e)-d)));z[a+24>>2]=b.getDay();z[a+28>>2]=(Na(b.getFullYear())?Oa:Pa)[b.getMonth()]+b.getDate()-1|0;z[a>>2]=b.getSeconds();z[a+4>>2]=b.getMinutes();z[a+8>>2]=b.getHours();
z[a+12>>2]=b.getDate();z[a+16>>2]=b.getMonth();z[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;Sc((E=a,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0));return a>>>0},ub:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=new Date(e,0,1),f=new Date(e,6,1);e=g.getTimezoneOffset();var n=f.getTimezoneOffset();A[a>>2]=60*Math.max(e,n);z[b>>2]=Number(e!=n);a=p=>p.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];g=a(g);f=a(f);n<
e?(G(g,y,c,17),G(f,y,d,17)):(G(g,y,d,17),G(f,y,c,17))},db:()=>{ib();Sa=null},Ea:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Ga:(a,b,c)=>{a=M(a);if(!a)return-4;a=Jb(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},B:Va,eb:()=>performance.now(),kb:(a,b)=>{function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},tb:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=
(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-qa.buffer.byteLength+65535)/65536;try{qa.grow(e);va();var g=1;break a}catch(f){}g=void 0}if(g)return!0}return!1},ma:(a,b,c,d)=>Mb(a,b,c,d,12,"blur"),Da:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},na:(a,b,c,d)=>Mb(a,b,c,d,13,"focus"),wa:(a,b,c,d)=>Nb(a,b,c,d,2,"keydown"),ua:(a,b,c,d)=>Nb(a,b,c,d,1,"keypress"),va:(a,b,c,d)=>Nb(a,b,c,d,3,"keyup"),mb:(a,b,c)=>{a=N(a);gb(a,b,c)},Ca:(a,b,c,d)=>Pb(a,b,c,d,5,"mousedown"),za:(a,b,c,d)=>Pb(a,
b,c,d,33,"mouseenter"),ya:(a,b,c,d)=>Pb(a,b,c,d,34,"mouseleave"),Aa:(a,b,c,d)=>Pb(a,b,c,d,8,"mousemove"),Ba:(a,b,c,d)=>Pb(a,b,c,d,6,"mouseup"),pa:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.zc||document.body.Tc||document.body.Sc))return-1;a=M(a);if(!a)return-4;Qb(a,b,c,d,"mozpointerlockchange");Qb(a,b,c,d,"webkitpointerlockchange");Qb(a,b,c,d,"mspointerlockchange");return Qb(a,b,c,d,"pointerlockchange")},oa:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||
document.body.zc||document.body.Tc||document.body.Sc))return-1;a=M(a);if(!a)return-4;Rb(a,b,c,d,"mozpointerlockerror");Rb(a,b,c,d,"webkitpointerlockerror");Rb(a,b,c,d,"mspointerlockerror");return Rb(a,b,c,d,"pointerlockerror")},Fa:(a,b,c,d)=>Sb(a,b,c,d),qa:(a,b,c,d)=>Tb(a,b,c,d,25,"touchcancel"),ra:(a,b,c,d)=>Tb(a,b,c,d,23,"touchend"),sa:(a,b,c,d)=>Tb(a,b,c,d,24,"touchmove"),ta:(a,b,c,d)=>Tb(a,b,c,d,22,"touchstart"),la:(a,b,c,d)=>{rc(a,b,c,d,31,"webglcontextlost");return 0},ka:(a,b,c,d)=>{rc(a,b,
c,d,32,"webglcontextrestored");return 0},xa:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?sc(a,b,c,d):-1:-4,jb:(a,b)=>{b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+5],powerPreference:tc[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],Jc:z[b+8],vd:z[b+9],Oc:z[b+10],cd:z[b+11],wd:z[b+12],yd:z[b+13]};a=M(a);return!a||b.cd?0:mc(a,b)},hb:(a,b)=>{a=fc[a];b=b?F(y,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==
b&&Ub(T);"OES_vertex_array_object"==b&&Vb(T);"WEBGL_draw_buffers"==b&&Wb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Xb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Yb(T);"WEBGL_multi_draw"==b&&(T.gd=T.getExtension("WEBGL_multi_draw"));return!!a.Bc.getExtension(b)},ib:a=>pc(a)?0:-5,rb:(a,b)=>{var c=0;wc().forEach((d,e)=>{var g=b+c;e=A[a+4*e>>2]=g;for(g=0;g<d.length;++g)sa[e++]=d.charCodeAt(g);sa[e]=0;c+=d.length+1});return 0},sb:(a,b)=>{var c=wc();A[a>>2]=c.length;var d=
0;c.forEach(e=>d+=e.length+1);A[b>>2]=d;return 0},Ha:()=>52,yb:()=>52,pb:function(){return 70},xb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=A[b>>2],n=A[b+4>>2];b+=8;for(var p=0;p<n;p++){var q=y[f+p],t=xc[a];0===q||10===q?((1===a?pa:l)(F(t,0)),t.length=0):t.push(q)}e+=n}A[d>>2]=e;return 0},l:a=>T.activeTexture(a),x:(a,b)=>{T.attachShader(P[a],Q[b])},La:(a,b,c)=>{T.bindAttribLocation(P[a],b,c?F(y,c):"")},c:(a,b)=>{35051==a?T.Mc=b:35052==a&&(T.vc=b);T.bindBuffer(a,ac[b])},a:(a,b,c)=>{T.bindBufferBase(a,
b,ac[c])},D:(a,b)=>{T.bindFramebuffer(a,bc[b])},Wa:(a,b)=>{T.bindRenderbuffer(a,cc[b])},o:(a,b)=>{T.bindSampler(a,S[b])},b:(a,b)=>{T.bindTexture(a,dc[b])},ja:a=>{T.bindVertexArray(ec[a])},ga:(a,b,c,d)=>T.blendColor(a,b,c,d),ha:(a,b)=>T.blendEquationSeparate(a,b),M:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),Hb:(a,b,c,d,e,g,f,n,p,q)=>T.blitFramebuffer(a,b,c,d,e,g,f,n,p,q),ba:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,y,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?y.subarray(c,c+b):b,d)},I:(a,b,c,d)=>
{2<=V.version?c&&T.bufferSubData(a,b,y,d,c):T.bufferSubData(a,b,y.subarray(d,d+c))},Ub:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),Pa:(a,b,c)=>{T.clearBufferfv(a,b,B,c>>2)},Tb:(a,b,c)=>{T.clearBufferiv(a,b,z,c>>2)},j:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},U:a=>{T.compileShader(Q[a])},Ua:(a,b,c,d,e,g,f,n)=>{2<=V.version?T.vc||!f?T.compressedTexImage2D(a,b,c,d,e,g,f,n):T.compressedTexImage2D(a,b,c,d,e,g,y,n,f):T.compressedTexImage2D(a,b,c,d,e,g,n?y.subarray(n,n+f):null)},Ta:(a,b,c,d,e,g,f,n,p)=>{T.vc?T.compressedTexImage3D(a,
b,c,d,e,g,f,n,p):T.compressedTexImage3D(a,b,c,d,e,g,f,y,p,n)},_:()=>{var a=jc(P),b=T.createProgram();b.name=a;b.Ec=b.Cc=b.Dc=0;b.Lc=1;P[a]=b;return a},W:a=>{var b=jc(Q);Q[b]=T.createShader(a);return b},K:a=>T.cullFace(a),ea:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=ac[d];e&&(T.deleteBuffer(e),e.name=0,ac[d]=null,d==T.Mc&&(T.Mc=0),d==T.vc&&(T.vc=0))}},u:(a,b)=>{for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=bc[d];e&&(T.deleteFramebuffer(e),e.name=0,bc[d]=null)}},y:a=>{if(a){var b=P[a];b?(T.deleteProgram(b),
b.name=0,P[a]=null):U||=1281}},da:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=cc[d];e&&(T.deleteRenderbuffer(e),e.name=0,cc[d]=null)}},J:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=S[d];e&&(T.deleteSampler(e),e.name=0,S[d]=null)}},s:a=>{if(a){var b=Q[a];b?(T.deleteShader(b),Q[a]=null):U||=1281}},z:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=dc[d];e&&(T.deleteTexture(e),e.name=0,dc[d]=null)}},Za:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2];T.deleteVertexArray(ec[d]);ec[d]=null}},O:a=>
T.depthFunc(a),N:a=>{T.depthMask(!!a)},d:a=>T.disable(a),A:a=>{T.disableVertexAttribArray(a)},i:(a,b,c)=>{T.drawArrays(a,b,c)},Jb:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Kb:(a,b,c,d)=>{T.drawElements(a,b,c,d)},Lb:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},f:a=>T.enable(a),R:a=>{T.enableVertexAttribArray(a)},Eb:()=>T.finish(),L:a=>T.frontFace(a),ca:(a,b)=>{kc(a,b,"createBuffer",ac)},Xa:(a,b)=>{kc(a,b,"createRenderbuffer",cc)},Ra:(a,b)=>{kc(a,b,"createSampler",S)},aa:(a,b)=>{kc(a,b,"createTexture",
dc)},cb:(a,b)=>{kc(a,b,"createVertexArray",ec)},Db:a=>T.generateMipmap(a),Vb:(a,b)=>T.getAttribLocation(P[a],b?F(y,b):""),g:()=>{var a=T.getError()||U;U=0;return a},h:(a,b)=>zc(a,b),Y:(a,b,c,d)=>{a=T.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,y,d,b):0;c&&(z[c>>2]=b)},F:(a,b,c)=>{if(c)if(a>=$b)U||=1281;else if(a=P[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.Ec)for(b=0;b<T.getProgramParameter(a,35718);++b)a.Ec=
Math.max(a.Ec,T.getActiveUniform(a,b).name.length+1);z[c>>2]=a.Ec}else if(35722==b){if(!a.Cc)for(b=0;b<T.getProgramParameter(a,35721);++b)a.Cc=Math.max(a.Cc,T.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.Cc}else if(35381==b){if(!a.Dc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Dc=Math.max(a.Dc,T.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.Dc}else z[c>>2]=T.getProgramParameter(a,b);else U||=1281},T:(a,b,c,d)=>{a=T.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,y,d,b):
0;c&&(z[c>>2]=b)},E:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(Q[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=T.getShaderParameter(Q[a],b):U||=1281},bb:(a,b)=>{if(2>V.version)return U||=1282,0;var c=gc[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=yc().map(Bc),c=gc[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},q:(a,b)=>{b=b?F(y,b):"";if(a=P[a]){var c=a,d=c.Ac,e=
c.ad,g;if(!d)for(c.Ac=d={},c.$c={},g=0;g<T.getProgramParameter(c,35718);++g){var f=T.getActiveUniform(c,g);var n=f.name;f=f.size;var p=Cc(n);p=0<p?n.slice(0,p):n;var q=c.Lc;c.Lc+=f;e[p]=[f,q];for(n=0;n<f;++n)d[q]=n,c.$c[q++]=p}c=a.Ac;d=0;e=b;g=Cc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.ad[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},Gb:(a,b,c)=>{for(var d=Dc[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];T.invalidateFramebuffer(a,d)},Z:a=>{a=
P[a];T.linkProgram(a);a.Ac=0;a.ad={}},e:(a,b)=>{3317==a?hc=b:3314==a&&(ic=b);T.pixelStorei(a,b)},fa:(a,b)=>T.polygonOffset(a,b),Ib:a=>T.readBuffer(a),Va:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),$:(a,b,c)=>{T.samplerParameterf(S[a],b,c)},k:(a,b,c)=>{T.samplerParameteri(S[a],b,c)},v:(a,b,c,d)=>T.scissor(a,b,c,d),V:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=A[c+4*g>>2])?F(y,f,d?A[d+4*g>>2]:void 0):"";e+=f}T.shaderSource(Q[a],e)},m:(a,b,c)=>T.stencilFunc(a,b,c),Oa:(a,b,c,d)=>T.stencilFuncSeparate(a,
b,c,d),r:a=>T.stencilMask(a),p:(a,b,c)=>T.stencilOp(a,b,c),C:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),H:(a,b,c,d,e,g,f,n,p)=>{if(2<=V.version){if(T.vc){T.texImage2D(a,b,c,d,e,g,f,n,p);return}if(p){var q=Ec(n);p>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,g,f,n,q,p);return}}q=p?Fc(n,f,d,e,p):null;T.texImage2D(a,b,c,d,e,g,f,n,q)},Sa:(a,b,c,d,e,g,f,n,p,q)=>{if(T.vc)T.texImage3D(a,b,c,d,e,g,f,n,p,q);else if(q){var t=Ec(p);T.texImage3D(a,b,c,d,e,g,f,n,p,t,q>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texImage3D(a,
b,c,d,e,g,f,n,p,null)},t:(a,b,c)=>T.texParameteri(a,b,c),Ma:(a,b,c,d,e,g,f,n,p)=>{if(2<=V.version){if(T.vc){T.texSubImage2D(a,b,c,d,e,g,f,n,p);return}if(p){var q=Ec(n);T.texSubImage2D(a,b,c,d,e,g,f,n,q,p>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}p=p?Fc(n,f,e,g,p):null;T.texSubImage2D(a,b,c,d,e,g,f,n,p)},Fb:(a,b,c,d,e,g,f,n,p,q,t)=>{if(T.vc)T.texSubImage3D(a,b,c,d,e,g,f,n,p,q,t);else if(t){var v=Ec(q);T.texSubImage3D(a,b,c,d,e,g,f,n,p,q,v,t>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,
b,c,d,e,g,f,n,p,q,null)},Sb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),B,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},X:(a,b)=>{T.uniform1i(W(a),b)},Qb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),z,c>>2,b);else{if(288>=b)for(var d=Gc[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},Na:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),B,c>>2,2*b);else{if(144>=b)for(var d=X[2*b],
e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},Pb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=Gc[2*b],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},Rb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3fv(W(a),B,c>>2,3*b);else{if(96>=b)for(var d=X[3*b],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>
2,c+12*b>>2);T.uniform3fv(W(a),d)}},Ob:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=Gc[3*b],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},P:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),B,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=B;c>>=2;for(var g=0;g<4*b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=B.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),
d)}},Nb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),z,c>>2,4*b);else{if(72>=b)for(var d=Gc[4*b],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},Mb:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=B;d>>=2;for(var f=0;f<16*b;f+=16){var n=d+f;e[f]=g[n];e[f+1]=g[n+1];e[f+2]=g[n+2];e[f+3]=g[n+3];e[f+4]=g[n+4];e[f+5]=g[n+5];e[f+6]=g[n+6];
e[f+7]=g[n+7];e[f+8]=g[n+8];e[f+9]=g[n+9];e[f+10]=g[n+10];e[f+11]=g[n+11];e[f+12]=g[n+12];e[f+13]=g[n+13];e[f+14]=g[n+14];e[f+15]=g[n+15]}}else e=B.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},n:a=>{a=P[a];T.useProgram(a);T.bd=a},ia:(a,b)=>{T.vertexAttribDivisor(a,b)},S:(a,b,c,d,e,g)=>{T.vertexAttribPointer(a,b,c,!!d,e,g)},w:(a,b,c,d)=>T.viewport(a,b,c,d),Xb:function(){h.Uc=a=>{0!=Tc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Uc)},gb:function(){h.Zc=
a=>{const b=a.clipboardData.getData("text");Pc(()=>{const c=Mc(b);Uc(c)})};window.addEventListener("paste",h.Zc)},$a:function(a){h.zd=[];a=a?F(y,a):"";a=document.getElementById(a);h.Vc=b=>{b.stopPropagation();b.preventDefault()};h.Wc=b=>{b.stopPropagation();b.preventDefault()};h.Xc=b=>{b.stopPropagation();b.preventDefault()};h.Yc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Ad=c;Vc(c.length);for(let e=0;e<c.length;e++)Pc(()=>{const g=Mc(c[e].name);Wc(e,g)});let d=0;b.shiftKey&&
(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Xc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",h.Vc,!1);a.addEventListener("dragleave",h.Wc,!1);a.addEventListener("dragover",h.Xc,!1);a.addEventListener("drop",h.Yc,!1)},Ya:function(a){a=a?F(y,a):"";h.wc=document.getElementById(a);h.wc||console.log("sokol_app.h: invalid target:"+a);h.wc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},lb:function(){window.removeEventListener("beforeunload",
h.Uc)},fb:function(){window.removeEventListener("paste",h.Zc)},_a:function(a){a=a?F(y,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",h.Vc);a.removeEventListener("dragleave",h.Wc);a.removeEventListener("dragover",h.Xc);a.removeEventListener("drop",h.Yc)},G:function(){h.wc&&h.wc.requestPointerLock&&h.wc.requestPointerLock()},Wb:function(a,b){if(h.wc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;
case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.wc.style.cursor=a}},ab:function(a){a=a?F(y,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=
1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Q:function(a,b,c,d,e,g){b=b?F(y,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const n=0<d;n&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!n){const p=new Uint8Array(f.response),q=p.length;q<=g?(y.set(p,e),Yc(a,d,q)):Zc(a)}else $c(a,f.status)};
f.send()},Qa:function(a,b){b=b?F(y,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");ad(a,d)}else $c(a,c.status)};c.send()},Ja:function(){return navigator.userAgent.includes("Macintosh")?1:0},Ka:function(a,b){b=b?F(y,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},Yb:Kc,qb:(a,b,c,d)=>
Kc(a,b,c,d)},Z=function(){function a(c){Z=c.exports;qa=Z.Zb;va();Lb=Z.lc;xa.unshift(Z._b);D--;h.monitorRunDependencies?.(D);0==D&&(null!==Ba&&(clearInterval(Ba),Ba=null),Ca&&(c=Ca,Ca=null,c()));return Z}var b={a:bd};D++;h.monitorRunDependencies?.(D);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}Fa||=Ea("solar-system.wasm")?"solar-system.wasm":h.locateFile?h.locateFile("solar-system.wasm",k):k+"solar-system.wasm";
Ja(b,function(c){a(c.instance)});return{}}(),Uc=h.__sapp_emsc_onpaste=a=>(Uc=h.__sapp_emsc_onpaste=Z.$b)(a),Tc=h.__sapp_html5_get_ask_leave_site=()=>(Tc=h.__sapp_html5_get_ask_leave_site=Z.ac)(),Vc=h.__sapp_emsc_begin_drop=a=>(Vc=h.__sapp_emsc_begin_drop=Z.bc)(a),Wc=h.__sapp_emsc_drop=(a,b)=>(Wc=h.__sapp_emsc_drop=Z.cc)(a,b),Xc=h.__sapp_emsc_end_drop=(a,b,c)=>(Xc=h.__sapp_emsc_end_drop=Z.dc)(a,b,c);
h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,n)=>(h.__sapp_emsc_invoke_fetch_cb=Z.ec)(a,b,c,d,e,g,f,n);
var cd=h._main=(a,b)=>(cd=h._main=Z.fc)(a,b),ad=h.__sfetch_emsc_head_response=(a,b)=>(ad=h.__sfetch_emsc_head_response=Z.gc)(a,b),Yc=h.__sfetch_emsc_get_response=(a,b,c)=>(Yc=h.__sfetch_emsc_get_response=Z.hc)(a,b,c),$c=h.__sfetch_emsc_failed_http_status=(a,b)=>($c=h.__sfetch_emsc_failed_http_status=Z.ic)(a,b),Zc=h.__sfetch_emsc_failed_buffer_too_small=a=>(Zc=h.__sfetch_emsc_failed_buffer_too_small=Z.jc)(a),O=a=>(O=Z.kc)(a),Sc=a=>(Sc=Z.mc)(a),Oc=a=>(Oc=Z.nc)(a),Lc=a=>(Lc=Z.oc)(a),Nc=()=>(Nc=Z.pc)(),
dd;Ca=function ed(){dd||fd();dd||(Ca=ed)};function gd(a=[]){var b=cd;a.unshift(fa);var c=a.length,d=Lc(4*(c+1)),e=d;a.forEach(f=>{A[e>>2]=Mc(f);e+=4});A[e>>2]=0;try{var g=b(c,d);hb(g)}catch(f){fb(f)}}
function fd(){var a=ea;function b(){if(!dd&&(dd=!0,h.calledRun=!0,!x)){Ka(xa);Ka(ya);if(h.onRuntimeInitialized)h.onRuntimeInitialized();hd&&gd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.unshift(c)}Ka(za)}}if(!(0<D)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();Ka(wa);0<D||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var hd=!0;h.noInitialRun&&(hd=!1);fd();
