var g;g||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},g),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,r,t;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=ia(a)?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};t=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=ia(a)?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ja||a.context instanceof ja))throw a;});k=(a,b)=>{process.exitCode=a;throw b;}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=q.startsWith("blob:")?"":q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1),fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=g.print||console.log.bind(console),v=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(k=g.quit);var w;g.wasmBinary&&(w=g.wasmBinary);"object"!=typeof WebAssembly&&la("no native wasm support detected");
var ma,na=!1,oa,x,pa,qa,z,A,B,C;function ra(){var a=ma.buffer;g.HEAP8=oa=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=x=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=z=new Int32Array(a);g.HEAPU32=A=new Uint32Array(a);g.HEAPF32=B=new Float32Array(a);g.HEAPF64=C=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];function wa(){var a=g.preRun.shift();sa.unshift(a)}var D=0,xa=null,E=null;
function la(a){g.onAbort?.(a);a="Aborted("+a+")";v(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),ia=a=>a.startsWith("file://"),F;F="two-body.wasm";if(!ya(F)){var za=F;F=g.locateFile?g.locateFile(za,q):q+za}function Aa(a){if(a==F&&w)return new Uint8Array(w);if(t)return t(a);throw"both async and sync fetching of the wasm failed";}
function Ba(a){if(!w&&(da||l)){if("function"==typeof fetch&&!ia(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Aa(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);la(d)})}
function Da(a,b){var c=F;w||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||ia(c)||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=a=>{for(;0<a.length;)a.shift()(g)},Fa=g.noExitRuntime||!0,Ga="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,G=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ja=a=>{var b=Ha();a();Ia(b)},Ka=0,La=[];function Ma(){if(navigator.userActivation?navigator.userActivation.isActive:Ka&&Na.oc)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.Vc(...b.Mc)}}var H=[];function Oa(a){var b=H[a];b.target.removeEventListener(b.bc,b.vc,b.cc);H.splice(a,1)}
function I(a){if(!a.target)return-4;if(a.dc)a.vc=function(c){++Ka;Na=a;Ma();a.ec(c);Ma();--Ka},a.target.addEventListener(a.bc,a.vc,a.cc),H.push(a);else for(var b=0;b<H.length;++b)H[b].target==a.target&&H[b].bc==a.bc&&Oa(b--);return 0}function Pa(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Na,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?G(x,a):"":a;return Xa[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ya=a=>0>Xa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Za=[],$a,K=a=>{var b=Za[a];b||(a>=Za.length&&(Za.length=a+1),Za[a]=b=$a.get(a));return b},L=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=
a.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},ab=(a,b,c,d,e,h)=>{Qa||=M(256);a={target:J(a),bc:h,dc:d,ec:(f=event)=>{var m=f.target.id?f.target.id:"",n=Qa;L(Pa(f.target),n+0,128);L(m,n+128,128);K(d)(e,n,b)&&f.preventDefault()},cc:c};return I(a)},bb=(a,
b,c,d,e,h)=>{Ra||=M(176);a={target:J(a),bc:h,dc:d,ec:f=>{var m=Ra;C[m>>3]=f.timeStamp;var n=m>>2;z[n+2]=f.location;z[n+3]=f.ctrlKey;z[n+4]=f.shiftKey;z[n+5]=f.altKey;z[n+6]=f.metaKey;z[n+7]=f.repeat;z[n+8]=f.charCode;z[n+9]=f.keyCode;z[n+10]=f.which;L(f.key||"",m+44,32);L(f.code||"",m+76,32);L(f.char||"",m+108,32);L(f.locale||"",m+140,32);K(d)(e,m,b)&&f.preventDefault()},cc:c};return I(a)},cb=(a,b,c)=>{C[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+
6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=b.altKey;z[a+9]=b.metaKey;pa[2*a+20]=b.button;pa[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=Ya(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top},N=(a,b,c,d,e,h)=>{Sa||=M(72);a=J(a);return I({target:a,oc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,bc:h,dc:d,ec:(f=event)=>{cb(Sa,f,a);K(d)(e,Sa,b)&&f.preventDefault()},cc:c})},db=(a,b,c,d,e)=>{Ta||=M(260);return I({target:a,bc:e,dc:d,ec:(h=event)=>{var f=Ta,m=document.pointerLockElement||
document.ic||document.sc||document.qc;z[f>>2]=!!m;var n=m?.id||"";L(Pa(m),f+4,128);L(n,f+132,128);K(d)(20,f,b)&&h.preventDefault()},cc:c})},eb=(a,b,c,d,e)=>I({target:a,bc:e,dc:d,ec:(h=event)=>{K(d)(38,0,b)&&h.preventDefault()},cc:c}),fb=(a,b,c,d)=>{Ua||=M(36);a=J(a);return I({target:a,bc:"resize",dc:d,ec:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=Ua;z[f>>2]=e.detail;z[f+4>>2]=h.clientWidth;z[f+8>>2]=h.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;
z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset;z[f+32>>2]=pageYOffset;K(d)(10,f,b)&&e.preventDefault()}}},cc:c})},gb=(a,b,c,d,e,h)=>{Va||=M(1696);a=J(a);return I({target:a,oc:"touchstart"==h||"touchend"==h,bc:h,dc:d,ec:f=>{for(var m,n={},p=f.touches,u=0;u<p.length;++u)m=p[u],m.wc=m.yc=0,n[m.identifier]=m;for(u=0;u<f.changedTouches.length;++u)m=f.changedTouches[u],m.wc=1,n[m.identifier]=m;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].yc=1;p=Va;C[p>>3]=f.timeStamp;var y=p>>2;
z[y+3]=f.ctrlKey;z[y+4]=f.shiftKey;z[y+5]=f.altKey;z[y+6]=f.metaKey;y+=7;var lb=Ya(a),mb=0;for(u in n)if(m=n[u],z[y]=m.identifier,z[y+1]=m.screenX,z[y+2]=m.screenY,z[y+3]=m.clientX,z[y+4]=m.clientY,z[y+5]=m.pageX,z[y+6]=m.pageY,z[y+7]=m.wc,z[y+8]=m.yc,z[y+9]=m.clientX-lb.left,z[y+10]=m.clientY-lb.top,y+=13,31<++mb)break;z[p+8>>2]=mb;K(d)(e,p,b)&&f.preventDefault()},cc:c})},hb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},ib=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},jb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},kb=a=>{a.Oc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
nb=a=>{a.Pc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},ob=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},pb=1,qb=[],O=[],rb=[],sb=[],tb=[],P=[],ub=[],vb=[],Q=[],wb={},xb=4,yb=a=>{for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b},T=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=R[c](),f=h&&yb(d);h?(h.name=f,d[f]=h):S||=1282;z[b+4*e>>2]=f}},Ab=(a,b)=>{a.ic||(a.ic=a.getContext,a.getContext=function(d,e){e=a.ic(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.xc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
zb(c,b):0},zb=(a,b)=>{var c=yb(vb),d={handle:c,attributes:b,version:b.xc,nc:a};a.canvas&&(a.canvas.Lc=d);vb[c]=d;("undefined"==typeof b.uc||b.uc)&&Bb(d);return c},Bb=a=>{a||=U;if(!a.Jc){a.Jc=!0;var b=a.nc;hb(b);ib(b);jb(b);kb(b);nb(b);2<=a.version&&(b.tc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.tc)b.tc=b.getExtension("EXT_disjoint_timer_query");b.Kc=b.getExtension("WEBGL_multi_draw");ob(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},
S,U,Cb=(a,b,c,d,e,h)=>{a={target:J(a),bc:h,dc:d,ec:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},cc:c};I(a)},Db=(a,b,c,d)=>{Wa||=M(104);return I({target:a,oc:!0,bc:"wheel",dc:d,ec:(e=event)=>{var h=Wa;cb(h,e,a);C[h+72>>3]=e.deltaX;C[h+80>>3]=e.deltaY;C[h+88>>3]=e.deltaZ;z[h+96>>2]=e.deltaMode;K(d)(9,h,b)&&e.preventDefault()},cc:c})},Eb=["default","low-power","high-performance"],Fb=[null,[],[]];function Gb(){var a=ob(R);return a=a.concat(a.map(b=>"GL_"+b))}
for(var Hb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>U.version){S||=1282;return}c=Gb().length;break;case 33307:case 33308:if(2>U.version){S||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":S||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:S||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){S||=1280;v(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:S||=1280;v(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}z[b>>2]=c}else S||=1281},Ib=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Jb=a=>{var b=Ib(a)+1,c=M(b);c&&L(a,c,b);return c},Kb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Lb=[],Mb=a=>{a-=5120;return 0==a?oa:1==a?x:2==a?pa:4==a?z:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?A:qa},Nb=(a,b,c,d,e)=>{a=Mb(a);var h=xb;b=d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+h-1&-h);return a.subarray(e>>>
31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},V=a=>{var b=R.Hc;if(b){var c=b.jc[a];"number"==typeof c&&(b.jc[a]=c=R.getUniformLocation(b,b.Fc[a]+(0<c?`[${c}]`:"")));return c}S||=1282},W=[],X=[],Ob=a=>{Fa||(g.onExit?.(a),na=!0);k(a,new ja(a))},Qb=a=>{var b=Ib(a)+1,c=Pb(b);L(a,c,b);return c},R,Y=0;32>Y;++Y)Lb.push(Array(Y));var Rb=new Float32Array(288);for(Y=0;288>Y;++Y)W[Y]=Rb.subarray(0,Y+1);var Sb=new Int32Array(288);for(Y=0;288>Y;++Y)X[Y]=Sb.subarray(0,Y+1);
var bc={Ea:function(){return 0},nb:function(){return 0},ob:function(){},ib:()=>1,j:()=>{la("")},Aa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Da:(a,b,c)=>{a=J(a);if(!a)return-4;a=Ya(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},Ha:()=>performance.now(),kb:(a,b,c)=>x.copyWithin(a,b,b+c),gb:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ma.buffer.byteLength+65535)/65536;try{ma.grow(e);ra();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},ia:(a,b,c,d)=>ab(a,b,c,d,12,"blur"),za:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},ja:(a,b,c,d)=>ab(a,b,c,d,13,"focus"),sa:(a,b,c,d)=>bb(a,b,c,d,2,"keydown"),qa:(a,b,c,d)=>bb(a,b,c,d,1,"keypress"),ra:(a,b,c,d)=>bb(a,b,c,d,3,"keyup"),ya:(a,b,c,d)=>N(a,b,c,d,5,"mousedown"),va:(a,
b,c,d)=>N(a,b,c,d,33,"mouseenter"),ua:(a,b,c,d)=>N(a,b,c,d,34,"mouseleave"),wa:(a,b,c,d)=>N(a,b,c,d,8,"mousemove"),xa:(a,b,c,d)=>N(a,b,c,d,6,"mouseup"),la:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ic||document.body.sc||document.body.qc))return-1;a=J(a);if(!a)return-4;db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");return db(a,b,c,d,"pointerlockchange")},ka:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||
document.body.ic||document.body.sc||document.body.qc))return-1;a=J(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,"mspointerlockerror");return eb(a,b,c,d,"pointerlockerror")},Ba:(a,b,c,d)=>fb(a,b,c,d),ma:(a,b,c,d)=>gb(a,b,c,d,25,"touchcancel"),na:(a,b,c,d)=>gb(a,b,c,d,23,"touchend"),oa:(a,b,c,d)=>gb(a,b,c,d,24,"touchmove"),pa:(a,b,c,d)=>gb(a,b,c,d,22,"touchstart"),ha:(a,b,c,d)=>{Cb(a,b,c,d,31,"webglcontextlost");return 0},ga:(a,b,c,d)=>{Cb(a,b,
c,d,32,"webglcontextrestored");return 0},ta:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Db(a,b,c,d):-1:-4,fb:(a,b)=>{b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+5],powerPreference:Eb[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],xc:z[b+8],Qc:z[b+9],uc:z[b+10],Ic:z[b+11],Rc:z[b+12],Sc:z[b+13]};a=J(a);return!a||b.Ic?0:Ab(a,b)},cb:(a,b)=>{a=vb[a];b=b?G(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==
b&&hb(R);"OES_vertex_array_object"==b&&ib(R);"WEBGL_draw_buffers"==b&&jb(R);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&kb(R);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&nb(R);"WEBGL_multi_draw"==b&&(R.Kc=R.getExtension("WEBGL_multi_draw"));return!!a.nc.getExtension(b)},db:a=>{U=vb[a];g.Nc=R=U?.nc;return!a||R?0:-5},Ca:()=>52,mb:()=>52,hb:function(){return 70},lb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=A[b>>2],m=A[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=x[f+n],u=Fb[a];0===
p||10===p?((1===a?ka:v)(G(u,0)),u.length=0):u.push(p)}e+=m}A[d>>2]=e;return 0},n:a=>R.activeTexture(a),x:(a,b)=>{R.attachShader(O[a],P[b])},Ga:(a,b,c)=>{R.bindAttribLocation(O[a],b,c?G(x,c):"")},b:(a,b)=>{35051==a?R.rc=b:35052==a&&(R.fc=b);R.bindBuffer(a,qb[b])},v:(a,b)=>{R.bindFramebuffer(a,rb[b])},Sa:(a,b)=>{R.bindRenderbuffer(a,sb[b])},q:(a,b)=>{R.bindSampler(a,Q[b])},a:(a,b)=>{R.bindTexture(a,tb[b])},ea:a=>{R.bindVertexArray(ub[a])},ca:(a,b,c,d)=>R.blendColor(a,b,c,d),da:(a,b)=>R.blendEquationSeparate(a,
b),M:(a,b,c,d)=>R.blendFuncSeparate(a,b,c,d),tb:(a,b,c,d,e,h,f,m,n,p)=>R.blitFramebuffer(a,b,c,d,e,h,f,m,n,p),$:(a,b,c,d)=>{2<=U.version?c&&b?R.bufferData(a,x,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?x.subarray(c,c+b):b,d)},y:(a,b,c,d)=>{2<=U.version?c&&R.bufferSubData(a,b,x,d,c):R.bufferSubData(a,b,x.subarray(d,d+c))},Hb:(a,b,c,d)=>R.clearBufferfi(a,b,c,d),La:(a,b,c)=>{R.clearBufferfv(a,b,B,c>>2)},Gb:(a,b,c)=>{R.clearBufferiv(a,b,z,c>>2)},h:(a,b,c,d)=>{R.colorMask(!!a,!!b,!!c,!!d)},D:a=>{R.compileShader(P[a])},
Pa:(a,b,c,d,e,h,f,m)=>{2<=U.version?R.fc||!f?R.compressedTexImage2D(a,b,c,d,e,h,f,m):R.compressedTexImage2D(a,b,c,d,e,h,x,m,f):R.compressedTexImage2D(a,b,c,d,e,h,m?x.subarray(m,m+f):null)},Oa:(a,b,c,d,e,h,f,m,n)=>{R.fc?R.compressedTexImage3D(a,b,c,d,e,h,f,m,n):R.compressedTexImage3D(a,b,c,d,e,h,f,x,n,m)},Y:()=>{var a=yb(O),b=R.createProgram();b.name=a;b.mc=b.kc=b.lc=0;b.pc=1;O[a]=b;return a},F:a=>{var b=yb(P);P[b]=R.createShader(a);return b},K:a=>R.cullFace(a),fa:(a,b)=>{for(var c=0;c<a;c++){var d=
z[b+4*c>>2],e=qb[d];e&&(R.deleteBuffer(e),e.name=0,qb[d]=null,d==R.rc&&(R.rc=0),d==R.fc&&(R.fc=0))}},u:(a,b)=>{for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=rb[d];e&&(R.deleteFramebuffer(e),e.name=0,rb[d]=null)}},P:a=>{if(a){var b=O[a];b?(R.deleteProgram(b),b.name=0,O[a]=null):S||=1281}},_a:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=sb[d];e&&(R.deleteRenderbuffer(e),e.name=0,sb[d]=null)}},Ya:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Q[d];e&&(R.deleteSampler(e),e.name=0,Q[d]=null)}},r:a=>{if(a){var b=
P[a];b?(R.deleteShader(b),P[a]=null):S||=1281}},Q:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=tb[d];e&&(R.deleteTexture(e),e.name=0,tb[d]=null)}},Xa:(a,b)=>{for(var c=0;c<a;c++){var d=z[b+4*c>>2];R.deleteVertexArray(ub[d]);ub[d]=null}},O:a=>R.depthFunc(a),N:a=>{R.depthMask(!!a)},c:a=>R.disable(a),z:a=>{R.disableVertexAttribArray(a)},g:(a,b,c)=>{R.drawArrays(a,b,c)},vb:(a,b,c,d)=>{R.drawArraysInstanced(a,b,c,d)},wb:(a,b,c,d)=>{R.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{R.drawElementsInstanced(a,
b,c,d,e)},d:a=>R.enable(a),T:a=>{R.enableVertexAttribArray(a)},qb:()=>R.finish(),L:a=>R.frontFace(a),aa:(a,b)=>{T(a,b,"createBuffer",qb)},Ta:(a,b)=>{T(a,b,"createRenderbuffer",sb)},Ma:(a,b)=>{T(a,b,"createSampler",Q)},_:(a,b)=>{T(a,b,"createTexture",tb)},Wa:(a,b)=>{T(a,b,"createVertexArray",ub)},pb:a=>R.generateMipmap(a),Ib:(a,b)=>R.getAttribLocation(O[a],b?G(x,b):""),e:()=>{var a=R.getError()||S;S=0;return a},f:(a,b)=>Hb(a,b),W:(a,b,c,d)=>{a=R.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");
b=0<b&&d?L(a,d,b):0;c&&(z[c>>2]=b)},H:(a,b,c)=>{if(c)if(a>=pb)S||=1281;else if(a=O[a],35716==b)a=R.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.mc)for(b=0;b<R.getProgramParameter(a,35718);++b)a.mc=Math.max(a.mc,R.getActiveUniform(a,b).name.length+1);z[c>>2]=a.mc}else if(35722==b){if(!a.kc)for(b=0;b<R.getProgramParameter(a,35721);++b)a.kc=Math.max(a.kc,R.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.kc}else if(35381==b){if(!a.lc)for(b=0;b<R.getProgramParameter(a,
35382);++b)a.lc=Math.max(a.lc,R.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.lc}else z[c>>2]=R.getProgramParameter(a,b);else S||=1281},V:(a,b,c,d)=>{a=R.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(z[c>>2]=b)},w:(a,b,c)=>{c?35716==b?(a=R.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=R.getShaderSource(P[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=R.getShaderParameter(P[a],b):S||=1281},$a:(a,b)=>{if(2>U.version)return S||=
1282,0;var c=wb[a];if(c)return 0>b||b>=c.length?(S||=1281,0):c[b];switch(a){case 7939:return c=Gb().map(Jb),c=wb[a]=c,0>b||b>=c.length?(S||=1281,0):c[b];default:return S||=1280,0}},l:(a,b)=>{b=b?G(x,b):"";if(a=O[a]){var c=a,d=c.jc,e=c.Gc,h;if(!d)for(c.jc=d={},c.Fc={},h=0;h<R.getProgramParameter(c,35718);++h){var f=R.getActiveUniform(c,h);var m=f.name;f=f.size;var n=Kb(m);n=0<n?m.slice(0,n):m;var p=c.pc;c.pc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Fc[p++]=n}c=a.jc;d=0;e=b;h=Kb(b);0<h&&(d=parseInt(b.slice(h+
1))>>>0,e=b.slice(0,h));if((e=a.Gc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||R.getUniformLocation(a,b)))return d}else S||=1281;return-1},sb:(a,b,c)=>{for(var d=Lb[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];R.invalidateFramebuffer(a,d)},X:a=>{a=O[a];R.linkProgram(a);a.jc=0;a.Gc={}},t:(a,b)=>{3317==a&&(xb=b);R.pixelStorei(a,b)},ba:(a,b)=>R.polygonOffset(a,b),ub:a=>R.readBuffer(a),Ra:(a,b,c,d,e)=>R.renderbufferStorageMultisample(a,b,c,d,e),Z:(a,b,c)=>{R.samplerParameterf(Q[a],b,c)},i:(a,b,c)=>{R.samplerParameteri(Q[a],
b,c)},B:(a,b,c,d)=>R.scissor(a,b,c,d),E:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=A[c+4*h>>2])?G(x,f,d?A[d+4*h>>2]:void 0):"";e+=f}R.shaderSource(P[a],e)},k:(a,b,c)=>R.stencilFunc(a,b,c),Ka:(a,b,c,d)=>R.stencilFuncSeparate(a,b,c,d),o:a=>R.stencilMask(a),m:(a,b,c)=>R.stencilOp(a,b,c),A:(a,b,c,d)=>R.stencilOpSeparate(a,b,c,d),J:(a,b,c,d,e,h,f,m,n)=>{if(2<=U.version)if(R.fc)R.texImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=Mb(m);R.texImage2D(a,b,c,d,e,h,f,m,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else R.texImage2D(a,
b,c,d,e,h,f,m,null);else R.texImage2D(a,b,c,d,e,h,f,m,n?Nb(m,f,d,e,n):null)},Na:(a,b,c,d,e,h,f,m,n,p)=>{if(R.fc)R.texImage3D(a,b,c,d,e,h,f,m,n,p);else if(p){var u=Mb(n);R.texImage3D(a,b,c,d,e,h,f,m,n,u,p>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else R.texImage3D(a,b,c,d,e,h,f,m,n,null)},s:(a,b,c)=>R.texParameteri(a,b,c),rb:(a,b,c,d,e,h,f,m,n)=>{if(2<=U.version)if(R.fc)R.texSubImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=Mb(m);R.texSubImage2D(a,b,c,d,e,h,f,m,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else R.texSubImage2D(a,
b,c,d,e,h,f,m,null);else p=null,n&&(p=Nb(m,f,e,h,n)),R.texSubImage2D(a,b,c,d,e,h,f,m,p)},Eb:(a,b,c)=>{if(2<=U.version)b&&R.uniform1fv(V(a),B,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);R.uniform1fv(V(a),d)}},G:(a,b)=>{R.uniform1i(V(a),b)},Cb:(a,b,c)=>{if(2<=U.version)b&&R.uniform1iv(V(a),z,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);R.uniform1iv(V(a),d)}},Ia:(a,b,c)=>{if(2<=U.version)b&&
R.uniform2fv(V(a),B,c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);R.uniform2fv(V(a),d)}},Bb:(a,b,c)=>{if(2<=U.version)b&&R.uniform2iv(V(a),z,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);R.uniform2iv(V(a),d)}},Db:(a,b,c)=>{if(2<=U.version)b&&R.uniform3fv(V(a),B,c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+
4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);R.uniform3fv(V(a),d)}},Ab:(a,b,c)=>{if(2<=U.version)b&&R.uniform3iv(V(a),z,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);R.uniform3iv(V(a),d)}},S:(a,b,c)=>{if(2<=U.version)b&&R.uniform4fv(V(a),B,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=B;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+
2]=e[f+2];d[h+3]=e[f+3]}}else d=B.subarray(c>>2,c+16*b>>2);R.uniform4fv(V(a),d)}},zb:(a,b,c)=>{if(2<=U.version)b&&R.uniform4iv(V(a),z,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);R.uniform4iv(V(a),d)}},yb:(a,b,c,d)=>{if(2<=U.version)b&&R.uniformMatrix4fv(V(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=W[16*b-1],h=B;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=h[m];e[f+
1]=h[m+1];e[f+2]=h[m+2];e[f+3]=h[m+3];e[f+4]=h[m+4];e[f+5]=h[m+5];e[f+6]=h[m+6];e[f+7]=h[m+7];e[f+8]=h[m+8];e[f+9]=h[m+9];e[f+10]=h[m+10];e[f+11]=h[m+11];e[f+12]=h[m+12];e[f+13]=h[m+13];e[f+14]=h[m+14];e[f+15]=h[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(V(a),!!c,e)}},p:a=>{a=O[a];R.useProgram(a);R.Hc=a},Fb:(a,b)=>{R.vertexAttribDivisor(a,b)},U:(a,b,c,d,e,h)=>{R.vertexAttribPointer(a,b,c,!!d,e,h)},C:(a,b,c,d)=>R.viewport(a,b,c,d),Kb:function(){g.zc=a=>{0!=Tb()&&(a.preventDefault(),
a.returnValue=" ")};window.addEventListener("beforeunload",g.zc)},bb:function(){g.Ec=a=>{const b=a.clipboardData.getData("text");Ja(()=>{const c=Qb(b);Ub(c)})};window.addEventListener("paste",g.Ec)},Va:function(a){g.Tc=[];a=a?G(x,a):"";a=document.getElementById(a);g.Ac=b=>{b.stopPropagation();b.preventDefault()};g.Bc=b=>{b.stopPropagation();b.preventDefault()};g.Cc=b=>{b.stopPropagation();b.preventDefault()};g.Dc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Uc=c;Vb(c.length);
for(let e=0;e<c.length;e++)Ja(()=>{const h=Qb(c[e].name);Wb(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Xb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Ac,!1);a.addEventListener("dragleave",g.Bc,!1);a.addEventListener("dragover",g.Cc,!1);a.addEventListener("drop",g.Dc,!1)},Qa:function(a){a=a?G(x,a):"";g.hc=document.getElementById(a);g.hc||console.log("sokol_app.h: invalid target:"+a);g.hc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},eb:function(){window.removeEventListener("beforeunload",g.zc)},ab:function(){window.removeEventListener("paste",g.Ec)},Ua:function(a){a=a?G(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Ac);a.removeEventListener("dragleave",g.Bc);a.removeEventListener("dragover",g.Cc);a.removeEventListener("drop",g.Dc)},I:function(){g.hc&&g.hc.requestPointerLock&&g.hc.requestPointerLock()},Jb:function(a,b){if(g.hc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.hc.style.cursor=a}},Za:function(a){a=a?G(x,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck",
"false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},R:function(a,b,c,d,e,h){b=b?G(x,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),
p=n.length;p<=h?(x.set(n,e),Yb(a,d,p)):Zb(a)}else $b(a,f.status)};f.send()},Ja:function(a,b){b=b?G(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");ac(a,d)}else $b(a,c.status)};c.send()},Fa:function(){return navigator.userAgent.includes("Macintosh")?1:0}},Z=function(){function a(c){Z=c.exports;ma=Z.Lb;ra();$a=Z.Zb;ta.unshift(Z.Mb);D--;g.monitorRunDependencies?.(D);
0==D&&(null!==xa&&(clearInterval(xa),xa=null),E&&(c=E,E=null,c()));return Z}var b={a:bc};D++;g.monitorRunDependencies?.(D);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return v(`Module.instantiateWasm callback failed with error: ${c}`),!1}Da(b,function(c){a(c.instance)});return{}}(),Ub=g.__sapp_emsc_onpaste=a=>(Ub=g.__sapp_emsc_onpaste=Z.Nb)(a),Tb=g.__sapp_html5_get_ask_leave_site=()=>(Tb=g.__sapp_html5_get_ask_leave_site=Z.Ob)(),Vb=g.__sapp_emsc_begin_drop=a=>(Vb=g.__sapp_emsc_begin_drop=
Z.Pb)(a),Wb=g.__sapp_emsc_drop=(a,b)=>(Wb=g.__sapp_emsc_drop=Z.Qb)(a,b),Xb=g.__sapp_emsc_end_drop=(a,b,c)=>(Xb=g.__sapp_emsc_end_drop=Z.Rb)(a,b,c);g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,m)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Sb)(a,b,c,d,e,h,f,m);
var cc=g._main=(a,b)=>(cc=g._main=Z.Tb)(a,b),ac=g.__sfetch_emsc_head_response=(a,b)=>(ac=g.__sfetch_emsc_head_response=Z.Ub)(a,b),Yb=g.__sfetch_emsc_get_response=(a,b,c)=>(Yb=g.__sfetch_emsc_get_response=Z.Vb)(a,b,c),$b=g.__sfetch_emsc_failed_http_status=(a,b)=>($b=g.__sfetch_emsc_failed_http_status=Z.Wb)(a,b),Zb=g.__sfetch_emsc_failed_buffer_too_small=a=>(Zb=g.__sfetch_emsc_failed_buffer_too_small=Z.Xb)(a),M=a=>(M=Z.Yb)(a),Ha=()=>(Ha=Z._b)(),Ia=a=>(Ia=Z.$b)(a),Pb=a=>(Pb=Z.ac)(a);
g.___start_em_js=550640;g.___stop_em_js=557714;var dc;E=function ec(){dc||fc();dc||(E=ec)};function gc(a=[]){var b=cc;a.unshift(ca);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(f=>{A[e>>2]=Qb(f);e+=4});A[e>>2]=0;try{var h=b(c,d);Ob(h)}catch(f){f instanceof ja||"unwind"==f||k(1,f)}}
function fc(){var a=ba;function b(){if(!dc&&(dc=!0,g.calledRun=!0,!na)){Ea(ta);Ea(ua);if(g.onRuntimeInitialized)g.onRuntimeInitialized();hc&&gc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ea(va)}}if(!(0<D)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Ea(sa);0<D||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var hc=!0;g.noInitialRun&&(hc=!1);fc();
